/* The stories of bakery (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'fraction-parts': { title: 'The last of the pie', scene: 'bakery', cast: ['koi', 'pixel'], beats: [
    { who: null, say: 'At the bakery counter, an apple pie has been cut into 4 equal slices. 3 slices are still in the tin.' },
    { who: 'pixel', say: 'Three slices! So it is three of a pie.' },
    { who: 'koi', say: 'Three slices, but not three pies. Count every slice first — all the equal pieces.', add: { t: '1 + 1 + 1 + 1', v: 4 } },
    { who: 'pixel', say: 'Four slices in the whole pie, and three of them are left.' },
    { who: 'koi', say: 'Then it is three out of four equal slices. Three quarters.', add: { t: '3/4', v: 0.75 } },
    { who: 'pixel', say: 'And the gap is one quarter — the slice I ate.', add: { t: '4/4 − 3/4', v: 0.25 } },
  ] },
  'fraction-of-amount': { title: 'Sharing the laddoos', scene: 'kitchen', cast: ['melody', 'pixel'], beats: [
    { who: null, say: 'There are 20 laddoos on the tray. Pip is allowed to take three quarters of them to the party.', add: { t: '3/4 of 20' } },
    { who: 'pixel', say: 'I will count them out one at a time… this could take a while.' },
    { who: 'melody', say: 'Quarters means share into 4 fair piles. How big is one pile?', add: { t: '20 ÷ 4', v: 5 } },
    { who: 'pixel', say: 'Five in each pile. And I get three of the piles.' },
    { who: 'melody', say: 'Three piles of five.', add: { t: '5 × 3', v: 15 } },
    { who: 'pixel', say: 'Fifteen laddoos. Divide by the bottom, times by the top!', add: { t: '20 ÷ 4 × 3', v: 15 } },
  ] },
  'equivalent-fractions': { title: 'Smaller slices', scene: 'bakery', cast: ['beaker', 'koi'], beats: [
    { who: null, say: 'Nova has 3 quarters of a cake. Rafi wants to cut it into twelfths, so more people can have a bite.', add: { t: '3/4' } },
    { who: 'koi', say: 'If you cut it smaller, do I end up with less cake?' },
    { who: 'beaker', say: 'No. I cut every quarter into 3. Four quarters become how many slices?', add: { t: '4 × 3', v: 12 } },
    { who: 'beaker', say: 'And your 3 quarters become…', add: { t: '3 × 3', v: 9 } },
    { who: 'koi', say: 'Nine twelfths. Same cake, just more pieces.', add: { t: '9/12', v: 0.75 } },
    { who: 'beaker', say: 'Do the same to the top and the bottom, and the share never changes.', add: { t: '3/4', v: 0.75 } },
  ] },
  'simplify-fractions': { title: 'The brownie tray', scene: 'kitchen', cast: ['panda', 'comet'], beats: [
    { who: null, say: 'A tray of brownies was cut into 16. Dax has eaten 12 of them.', add: { t: '12/16', v: 0.75 } },
    { who: 'comet', say: 'Twelve sixteenths. That sounds like a lot of numbers for some brownies.' },
    { who: 'panda', say: 'Glue the pieces back together. What is the biggest number that goes into 12 and 16?', add: { t: '16 ÷ 4', v: 4 } },
    { who: 'comet', say: 'Four. Twelve divided by four…', add: { t: '12 ÷ 4', v: 3 } },
    { who: 'panda', say: 'Three of four bigger pieces. Three quarters.', add: { t: '3/4', v: 0.75 } },
    { who: 'comet', say: 'Three quarters of a tray. That sounds even worse.' },
  ] },
  'compare-fractions': { title: 'Two birthday cakes', scene: 'festival', cast: ['scopey', 'melody'], beats: [
    { who: null, say: 'Two cakes at the party, the same size. 3/5 of the lemon cake is left and 4/7 of the chocolate one.' },
    { who: 'scopey', say: 'Which has more left? Fifths and sevenths do not match.' },
    { who: 'melody', say: 'Cut both into thirty-fifths in your head. You only need the new tops.' },
    { who: 'melody', say: 'Lemon: 3 times 7.', add: { t: '3 × 7', v: 21 } },
    { who: 'scopey', say: 'Chocolate: 4 times 5.', add: { t: '4 × 5', v: 20 } },
    { who: 'melody', say: '21 is more than 20, so there is more lemon cake — only just.', add: { t: '21 − 20', v: 1 } },
    { who: 'scopey', say: 'I checked the decimals too. Three fifths is a little bigger.', add: { t: '3/5', v: 0.6 } },
  ] },
  'add-same-bottom': { title: 'Seven-slice pizza', scene: 'kitchen', cast: ['koi', 'comet'], beats: [
    { who: null, say: 'A pizza is cut into 7 equal slices. Dax eats 2 slices, and Nova eats 3.', add: { t: '2/7 + 3/7' } },
    { who: 'comet', say: 'Two plus three is five, seven plus seven is fourteen — five fourteenths!' },
    { who: 'koi', say: 'Did the pizza grow to fourteen slices while we ate it?' },
    { who: 'comet', say: 'Ah. No. It is still sevenths.' },
    { who: 'koi', say: 'So just count the slices we ate: that is the top.' },
    { who: 'comet', say: 'Five sevenths. The bottom is the size of the slice, and that did not change.', add: { t: '2 + 3', v: 5 } },
  ] },
  'mixed-numbers': { title: 'Pies in quarters', scene: 'bakery', cast: ['beaker', 'pixel'], beats: [
    { who: null, say: 'The bakery sells pie by the quarter. There are 2 whole pies and 3 extra quarters on the shelf.' },
    { who: 'pixel', say: 'How many quarter-slices can they sell?' },
    { who: 'beaker', say: 'Every whole pie is 4 quarters. Two pies…', add: { t: '2 × 4', v: 8 } },
    { who: 'beaker', say: '…and the 3 extra quarters.', add: { t: '8 + 3', v: 11 } },
    { who: 'pixel', say: 'Eleven quarters! And eleven quarters is back to 2 pies and 3 left.', add: { t: '11 − 2 × 4', v: 3 } },
    { who: 'beaker', say: 'Two names for the same pile of pie.', add: { t: '11/4', v: 2.75 } },
  ] },
  'add-different-bottoms': { title: 'Flour in two jugs', scene: 'bakery', cast: ['astro', 'beaker'], beats: [
    { who: null, say: 'Mira pours 1/3 of a jug of milk into the bowl, then 1/4 of a jug more.', add: { t: '1/3 + 1/4' } },
    { who: 'beaker', say: 'Thirds and quarters. We cannot add those yet.' },
    { who: 'astro', say: 'Find a size of piece both fit into. Twelfths — 3 and 4 both go into 12.', add: { t: '3 × 4', v: 12 } },
    { who: 'astro', say: 'One third is four twelfths.', add: { t: '12 ÷ 3', v: 4 } },
    { who: 'beaker', say: 'One quarter is three twelfths.', add: { t: '12 ÷ 4', v: 3 } },
    { who: 'astro', say: 'Four twelfths and three twelfths make seven twelfths of a jug.', add: { t: '4 + 3', v: 7 } },
  ] },
  'multiply-fractions': { title: 'Half of the rest', scene: 'kitchen', cast: ['samurai', 'koi'], beats: [
    { who: null, say: 'Three quarters of a tray of flapjack is left. Kwame says Nova can have two thirds of what is left.', add: { t: '2/3 × 3/4' } },
    { who: 'koi', say: 'Two thirds OF three quarters. How much of the whole tray is that?' },
    { who: 'samurai', say: 'Cut the tray in 3 rows and 4 columns. How many squares?', add: { t: '3 × 4', v: 12 } },
    { who: 'samurai', say: 'Three columns are left, and you take 2 rows of them.', add: { t: '2 × 3', v: 6 } },
    { who: 'koi', say: 'Six squares out of twelve. Half the tray!', add: { t: '6/12', v: 0.5 } },
    { who: 'samurai', say: 'Tops times tops, bottoms times bottoms.', add: { t: '2/3 × 3/4', v: 0.5 } },
  ] },
  'divide-fractions': { title: 'How many helpings?', scene: 'bakery', cast: ['goldlegend', 'comet'], beats: [
    { who: null, say: 'The bakery has 6 cakes. One helping is two thirds of a cake. How many helpings is that?', add: { t: '6 ÷ 2/3' } },
    { who: 'comet', say: 'Dividing should make it smaller. Four? Three?' },
    { who: 'goldlegend', say: 'Count thirds first.', add: { t: '6 × 3', v: 18 } },
    { who: 'goldlegend', say: 'Two thirds each.', add: { t: '18 ÷ 2', v: 9 } },
    { who: 'comet', say: 'Nine helpings — more than six! Because each one is less than a cake.' },
    { who: 'goldlegend', say: 'Times by 3, divide by 2. Flip it and multiply.', add: { t: '6 × 3 ÷ 2', v: 9 } },
  ] },
};
