/* The stories of carnival (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'pictogram-total': { title: 'The prize board', scene: 'carnival', cast: ['pixel', 'koi'], beats: [
    { who: null, say: 'The carnival prize board uses stars. Next to Hoopla there are 4 whole stars and a half star. The key says one star is 4 prizes.' },
    { who: 'pixel', say: 'Four and a half stars — so four and a half prizes?' },
    { who: 'koi', say: 'Read the key first. Each star is a bag of 4 prizes. Four whole stars…', add: { t: '4 × 4', v: 16 } },
    { who: 'pixel', say: 'And the half star is half a bag.', add: { t: '4 ÷ 2', v: 2 } },
    { who: 'koi', say: 'Put them together.', add: { t: '16 + 2', v: 18 } },
    { who: 'pixel', say: 'Eighteen prizes at Hoopla! The stars were only the bags.', add: { t: '4 × 4 + 2', v: 18 } },
  ] },
  'bar-compare': { title: 'The ride vote', scene: 'fair', cast: ['comet', 'scopey'], beats: [
    { who: null, say: 'The fair asked everyone to vote for their favourite ride. The bar chart has a tall bar for the Big Wheel and a shorter one for the Teacups.' },
    { who: 'comet', say: 'The Wheel won by loads!' },
    { who: 'scopey', say: 'By how many, though? Read across from the top of each bar. The Wheel reaches 34.', add: { t: '34' } },
    { who: 'comet', say: 'And the Teacups stops halfway between 20 and 22… 21.' },
    { who: 'scopey', say: 'The gap between the two tops is the difference.', add: { t: '34 − 21', v: 13 } },
    { who: 'comet', say: 'Thirteen more votes. Not loads — thirteen.', add: { t: '21 + 13', v: 34 } },
  ] },
  'chance-words': { title: 'The lucky dip', scene: 'carnival', cast: ['panda', 'pixel'], beats: [
    { who: null, say: 'At the lucky dip, a bag holds 3 yellow balls and 5 blue ones. Blue wins a prize.' },
    { who: 'pixel', say: 'I am going to get blue. Definitely. It is certain!' },
    { who: 'panda', say: 'Certain would mean every ball is blue. How many balls are there altogether?', add: { t: '3 + 5', v: 8 } },
    { who: 'pixel', say: 'Eight. And five of them are blue.' },
    { who: 'panda', say: 'Half of eight would be four. Five is more than half.', add: { t: '8 ÷ 2', v: 4 } },
    { who: 'pixel', say: 'So blue is likely. Not certain — just likely.' },
    { who: 'panda', say: 'And a green ball? There are none. That one is impossible.' },
  ] },
  'line-graph-read': { title: 'The hot afternoon', scene: 'stadium', cast: ['astro', 'comet'], beats: [
    { who: null, say: 'The stadium screen shows a line graph of the temperature. At 11 o’clock the line is at 20 degrees; at noon it is at 24.' },
    { who: 'comet', say: 'We got here at half past eleven. How hot was it then? There is no dot.' },
    { who: 'astro', say: 'The line joins the dots. Half past eleven is halfway along it, so halfway between 20 and 24.' },
    { who: 'astro', say: 'The gap is 4 degrees.', add: { t: '24 − 20', v: 4 } },
    { who: 'comet', say: 'Half of that is 2.', add: { t: '4 ÷ 2', v: 2 } },
    { who: 'astro', say: 'So add it to 20.', add: { t: '20 + 2', v: 22 } },
    { who: 'comet', say: 'Twenty-two degrees. Up, across, and read.', add: { t: '(20 + 24) ÷ 2', v: 22 } },
  ] },
  'mean-fair-share': { title: 'Sharing the tickets', scene: 'carnival', cast: ['koi', 'beaker'], beats: [
    { who: null, say: 'Four friends play the games. Nova wins 3 tickets, Rafi 7, Pip 5 and Suki 9. They agree to share them fairly.', add: { t: '3 + 7 + 5 + 9' } },
    { who: 'beaker', say: 'Tip them all into one pile first. Nothing gets lost.', add: { t: '3 + 7 + 5 + 9', v: 24 } },
    { who: 'koi', say: 'Now deal them out, one each, round and round, between the four of us.', add: { t: '24 ÷ 4', v: 6 } },
    { who: 'beaker', say: 'Six each. That fair share has a name: the mean.' },
    { who: 'koi', say: 'Suki gave up 3, I gained 3 — it all levels out.', add: { t: '6 × 4', v: 24 } },
  ] },
  'median-mode': { title: 'The coconut shy', scene: 'fair', cast: ['scopey', 'melody'], beats: [
    { who: null, say: 'Five throws at the coconut shy score 12, 5, 9, 14 and 7 points. Ines wants the middle score.' },
    { who: 'melody', say: 'The middle one is 9 — it is third on the list.' },
    { who: 'scopey', say: 'Only if they are in order. Line them up: 5, 7, 9, 12, 14.', add: { t: '5 + 7 + 9 + 12 + 14', v: 47 } },
    { who: 'melody', say: 'Five scores, so the middle is the third one.', add: { t: '(5 + 1) ÷ 2', v: 3 } },
    { who: 'scopey', say: 'And the third one in order is 9. You were right — but by luck.', add: { t: '12 − 3', v: 9 } },
    { who: 'melody', say: 'The median is 9. Order first, then find the middle.' },
  ] },
  'data-range': { title: 'Two cricket teams', scene: 'cricket', cast: ['samurai', 'pixel'], beats: [
    { who: null, say: 'The Reds scored 14, 31, 25, 9 and 27 runs. Pip wants to know how spread out the scores are.' },
    { who: 'pixel', say: 'Do I need all five numbers?' },
    { who: 'samurai', say: 'Only the ends. The biggest is 31, the smallest is 9.' },
    { who: 'samurai', say: 'The range is the distance between them.', add: { t: '31 − 9', v: 22 } },
    { who: 'pixel', say: 'The other scores are all in between, so they cannot stretch it.' },
    { who: 'samurai', say: 'A range of 22 runs.', add: { t: '9 + 22', v: 31 } },
  ] },
  'chance-fraction': { title: 'The spinner stall', scene: 'carnival', cast: ['melody', 'comet'], beats: [
    { who: null, say: 'The spinner has 8 equal parts. 3 are blue, and blue wins a goldfish balloon.' },
    { who: 'comet', say: 'What are my chances?' },
    { who: 'melody', say: 'Each part is the same size, so each has one eighth of the chance.', add: { t: '1 ÷ 8', v: 0.125 } },
    { who: 'melody', say: 'Three of the parts are blue — three eighths.', add: { t: '3 × 0.125', v: 0.375 } },
    { who: 'comet', say: 'And the chance of NOT blue is the rest.', add: { t: '8 − 3', v: 5 } },
    { who: 'melody', say: 'Five eighths. Your chance of blue is 3 out of 8.', add: { t: '3 ÷ 8', v: 0.375 } },
  ] },
  'list-outcomes': { title: 'Parade costumes', scene: 'hall', cast: ['astro', 'koi'], beats: [
    { who: null, say: 'Before the parade, the costume box holds 3 tops and 4 skirts. Nova wants a different outfit every day.' },
    { who: 'koi', say: 'I will draw every outfit. This could take a while.' },
    { who: 'astro', say: 'Do it in a system. The first top goes with all 4 skirts.' },
    { who: 'koi', say: 'Then the second top with all 4, and the third with all 4.', add: { t: '4 + 4 + 4', v: 12 } },
    { who: 'astro', say: 'Three rows of four. That is just a times.', add: { t: '3 × 4', v: 12 } },
    { who: 'koi', say: 'Twelve outfits — twelve days of parades!' },
  ] },
  'think-of-a-number': { title: 'The mind-reader', scene: 'carnival', cast: ['goldlegend', 'pixel'], beats: [
    { who: null, say: 'A sign on the tent says "The Mind-Reader". Pip thinks of a number, times it by 3, adds 4, and says: "19".' },
    { who: 'pixel', say: 'You cannot possibly know my number.' },
    { who: 'goldlegend', say: 'Last thing you did was add 4. Undo it.', add: { t: '19 − 4', v: 15 } },
    { who: 'goldlegend', say: 'Before that you timesed by 3. Undo that too.', add: { t: '15 ÷ 3', v: 5 } },
    { who: 'pixel', say: 'Five! How?' },
    { who: 'goldlegend', say: 'Backwards, last step first. Check it.', add: { t: '5 × 3 + 4', v: 19 } },
  ] },
  'multi-step-problems': { title: 'Tokens at the fair', scene: 'market', cast: ['melody', 'beaker'], beats: [
    { who: null, say: 'Rafi has 50 tokens. He goes on 3 rides that cost 8 tokens each.' },
    { who: 'beaker', say: 'How many are left? I cannot take anything away yet.' },
    { who: 'melody', say: 'Right — first you need what you spent. Three rides at 8.', add: { t: '3 × 8', v: 24 } },
    { who: 'beaker', say: 'Now take that from what I started with.', add: { t: '50 − 24', v: 26 } },
    { who: 'melody', say: 'Does it make sense? Less than 50, more than none. Yes.' },
    { who: 'beaker', say: 'Twenty-six tokens left. Two little sums, in the right order.', add: { t: '50 − 3 × 8', v: 26 } },
  ] },
  'who-has-which': { title: 'The prize mix-up', scene: 'garden', cast: ['panda', 'scopey'], beats: [
    { who: null, say: 'Suki, Theo and Nova each won one prize: a kite, a teddy or a yo-yo. The labels fell off, and there are 2 clues.' },
    { who: 'scopey', say: 'Clue one: Suki did not win the kite. Clue two: Theo won the teddy.' },
    { who: 'panda', say: 'Draw a grid: 3 people, 3 prizes.', add: { t: '3 × 3', v: 9 } },
    { who: 'panda', say: 'Theo has the teddy, so nobody else can. That tick crosses out a row and a column.' },
    { who: 'scopey', say: 'So Suki cannot have the kite or the teddy. Only the yo-yo is left for her.' },
    { who: 'panda', say: 'And Nova gets the last one: the kite. Three prizes, three people.', add: { t: '9 − 6', v: 3 } },
  ] },
  'factorials': { title: 'The photo booth', scene: 'fair', cast: ['beaker', 'comet'], beats: [
    { who: null, say: 'At the fair photo booth, 5 friends want a picture in a row. Dax wants one photo for every different order.' },
    { who: 'comet', say: 'Easy. Five people — maybe twenty orders? I will just try them all.' },
    { who: 'beaker', say: 'Fill the row from the left. Any of the 5 can go first, then any of the 4 left.', add: { t: '5 × 4', v: 20 } },
    { who: 'comet', say: 'Twenty already, and that is only two places. Then 3 for the middle, 2, and the last one has no choice.', add: { t: '20 × 3 × 2 × 1', v: 120 } },
    { who: 'beaker', say: 'At one click a second, that is two whole minutes of photos.', add: { t: '120 ÷ 60', v: 2 } },
    { who: 'comet', say: 'Every number from 5 down to 1, multiplied. Is there a name for that?' },
    { who: 'beaker', say: 'Five factorial, written 5 with an exclamation mark. 120 orders.', add: { t: '5 × 4 × 3 × 2 × 1', v: 120 } },
  ] },
  'arrange-all': { title: 'The dodgem queue', scene: 'carnival', cast: ['pixel', 'panda'], beats: [
    { who: null, say: 'Pip, Suki, Nova and Rafi queue for the dodgems. Pip says he must be at the front.' },
    { who: 'pixel', say: 'Front is mine. How many ways can the rest of you stand behind me?' },
    { who: 'panda', say: 'Your place has only one choice now. That leaves three of us to arrange.', add: { t: '4 − 1', v: 3 } },
    { who: 'pixel', say: 'Three for the second place, two for the third, one for the last.', add: { t: '3 × 2 × 1', v: 6 } },
    { who: 'panda', say: 'Without your rule it would have been all four of us in any order.', add: { t: '4 × 3 × 2 × 1', v: 24 } },
    { who: 'pixel', say: 'So my rule keeps a quarter of them: 6 orders, every one with me in front.', add: { t: '24 ÷ 4', v: 6 } },
  ] },
  'permutations': { title: 'The medal table', scene: 'stadium', cast: ['scopey', 'samurai'], beats: [
    { who: null, say: 'Eight runners line up for the final at the stadium. There are gold, silver and bronze medals to give out.' },
    { who: 'scopey', say: 'How many different ways could the medals go? All eight in order — is it 8 factorial?' },
    { who: 'samurai', say: 'Only three places get a medal. Any of the 8 could take gold, then 7 are left for silver.', add: { t: '8 × 7', v: 56 } },
    { who: 'scopey', say: 'And 6 left for bronze.', add: { t: '56 × 6', v: 336 } },
    { who: 'samurai', say: 'The last five get no medal, so their order does not count. Cut the tail off 8 factorial.' },
    { who: 'scopey', say: 'Three hundred and thirty-six ways. Checked.', add: { t: '8 × 7 × 6', v: 336 } },
  ] },
  'combinations': { title: 'Picking the quiz team', scene: 'hall', cast: ['koi', 'goldlegend'], beats: [
    { who: null, say: 'Seven children want to be in the quiz final, but a team is only 3. Nova is counting the possible teams.' },
    { who: 'koi', say: 'Seven for the first place, six for the second, five for the third.', add: { t: '7 × 6 × 5', v: 210 } },
    { who: 'goldlegend', say: 'A team has no first place.' },
    { who: 'koi', say: 'Oh. Asha, Ben and Chen is the same team as Chen, Ben and Asha. How many orders does one team have?', add: { t: '3 × 2 × 1', v: 6 } },
    { who: 'goldlegend', say: 'So every team was counted 6 times.', add: { t: '210 ÷ 6', v: 35 } },
    { who: 'koi', say: 'Thirty-five teams. Count in order, then divide by the orders.', add: { t: '7 × 6 × 5 ÷ (3 × 2 × 1)', v: 35 } },
  ] },
};
