/* The stories of clocktower (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'read-the-clock': { title: 'The tower clock', scene: 'clock', cast: ['koi', 'pixel'], beats: [
    { who: null, say: 'Pip and Nova look up at the clock tower. The long hand points at the 9. The short hand is nearly at the 4.' },
    { who: 'pixel', say: 'The short hand is nearly at 4, so it is four o\'clock-ish. And the 9 means… nine minutes?' },
    { who: 'koi', say: 'Each number is five minutes for the long hand. Count in fives to the 9.', add: { t: '9 × 5', v: 45 } },
    { who: 'pixel', say: 'Forty-five minutes past! But past which hour?' },
    { who: 'koi', say: 'The short hand has not reached the 4 yet, so it is still the 3 o\'clock hour.' },
    { who: 'pixel', say: 'So it is 3:45 — and 15 minutes until four.', add: { t: '60 − 45', v: 15 } },
  ] },
  'giving-change': { title: 'The comic stall', scene: 'market', cast: ['melody', 'comet'], beats: [
    { who: null, say: 'At the market, Dax buys a comic for 37 coins. He pays with 50 coins.', add: { t: '50 − 37' } },
    { who: 'comet', say: 'Fifty take away thirty-seven… borrow the one… I always get muddled.' },
    { who: 'melody', say: 'Do what the stallholder does — count up from the price. 37 up to 40.', add: { t: '40 − 37', v: 3 } },
    { who: 'comet', say: 'Then 40 up to 50.', add: { t: '50 − 40', v: 10 } },
    { who: 'melody', say: 'Add the jumps.', add: { t: '3 + 10', v: 13 } },
    { who: 'comet', say: 'Thirteen coins change. No borrowing at all.', add: { t: '50 − 37', v: 13 } },
  ] },
  'how-long': { title: 'The film on the train', scene: 'train', cast: ['scopey', 'pixel'], beats: [
    { who: null, say: 'On a long train ride, Pip starts a film at 2:40. It ends at 4:15.' },
    { who: 'pixel', say: '415 take away 240 is 175. A 175-minute film!' },
    { who: 'scopey', say: 'Check it. Clocks roll over at 60, not 100. Jump to 3:00 first.', add: { t: '60 − 40', v: 20 } },
    { who: 'pixel', say: 'Then 3:00 to 4:00 is a whole hour.', add: { t: '1 × 60', v: 60 } },
    { who: 'scopey', say: 'And 4:00 to 4:15.', add: { t: '15', v: 15 } },
    { who: 'pixel', say: 'Add the jumps: 95 minutes. Much shorter than I said!', add: { t: '20 + 60 + 15', v: 95 } },
  ] },
  'twenty-four-hour': { title: 'The evening train', scene: 'bus', cast: ['panda', 'comet'], beats: [
    { who: null, say: 'At the bus station, the board says the last bus leaves at 19:45.' },
    { who: 'comet', say: '19 o\'clock? Clocks only go up to 12!' },
    { who: 'panda', say: 'The 24-hour clock keeps counting after midday. Take away the 12 of the morning.', add: { t: '19 − 12', v: 7 } },
    { who: 'comet', say: 'So 19:45 is 7:45 in the evening. Plenty of time for dinner.' },
    { who: 'panda', say: 'And going the other way, 3 pm is 3 hours after midday.', add: { t: '3 + 12', v: 15 } },
    { who: 'comet', say: 'So 3 pm is 15:00, and our bus is at 7:45 pm.', add: { t: '19 − 12', v: 7 } },
  ] },
  'metric-units': { title: 'The ribbon and the flour', scene: 'kitchen', cast: ['beaker', 'koi'], beats: [
    { who: null, say: 'In the kitchen, Nova measures ribbon for a cake: 3 m 45 cm. The recipe wants it in centimetres.' },
    { who: 'beaker', say: 'Centi- means a hundredth, so 100 cm make one metre.' },
    { who: 'koi', say: 'Three metres is three lots of 100.', add: { t: '3 × 100', v: 300 } },
    { who: 'beaker', say: 'Then add the 45 cm on the end.', add: { t: '300 + 45', v: 345 } },
    { who: 'koi', say: 'And the flour: 2 kg. Kilo- means a thousand.', add: { t: '2 × 1000', v: 2000 } },
    { who: 'beaker', say: 'So the ribbon is 345 cm. Bigger unit to smaller: multiply.', add: { t: '3 × 100 + 45', v: 345 } },
  ] },
  perimeter: { title: 'Fencing the vegetable patch', scene: 'garden', cast: ['samurai', 'pixel'], beats: [
    { who: null, say: 'Kwame and Pip are putting a fence round a vegetable patch 8 m long and 5 m wide.' },
    { who: 'pixel', say: 'Eight and five — thirteen metres of fence!', add: { t: '8 + 5', v: 13 } },
    { who: 'samurai', say: 'Walk round it. That is only one length and one width — half way.' },
    { who: 'pixel', say: 'Oh. There is another length and another width on the far side.' },
    { who: 'samurai', say: 'So double it.', add: { t: '2 × 13', v: 26 } },
    { who: 'pixel', say: 'Twenty-six metres of fence, all the way round.', add: { t: '8 + 5 + 8 + 5', v: 26 } },
  ] },
  'area-rectangles': { title: 'The new rug', scene: 'room', cast: ['astro', 'comet'], beats: [
    { who: null, say: 'Dax\'s family has a new rug with a square pattern: 7 squares long and 6 squares wide.' },
    { who: 'comet', say: 'One, two, three… I will count every square.' },
    { who: 'astro', say: 'Every row has the same number. How many in one row?', add: { t: '7', v: 7 } },
    { who: 'comet', say: 'Seven. And there are 6 rows.' },
    { who: 'astro', say: 'Six equal rows of seven is a times table.', add: { t: '6 × 7', v: 42 } },
    { who: 'comet', say: 'Forty-two squares. Length times width!', add: { t: '7 × 6', v: 42 } },
  ] },
  'compound-area': { title: 'Carpet for the L-shaped hall', scene: 'hall', cast: ['beaker', 'melody'], beats: [
    { who: null, say: 'A hall is shaped like an L: 8 m across the bottom, 7 m up the side, with a corner missing.' },
    { who: 'melody', say: 'It is not a rectangle, so length times width will not work.' },
    { who: 'beaker', say: 'Cut it into two rectangles. The bottom strip is 8 m by 3 m.', add: { t: '8 × 3', v: 24 } },
    { who: 'melody', say: 'The part above is 3 m wide and 7 − 3 = 4 m tall.', add: { t: '3 × 4', v: 12 } },
    { who: 'beaker', say: 'Check it the other way: the full rectangle, minus the missing corner.', add: { t: '8 × 7 − 5 × 4', v: 36 } },
    { who: 'melody', say: 'Both roads agree — 36 square metres of carpet.', add: { t: '24 + 12', v: 36 } },
  ] },
  'area-triangles': { title: 'The market awning', scene: 'market', cast: ['goldlegend', 'scopey'], beats: [
    { who: null, say: 'A stall awning is a leaning parallelogram: base 9 m, straight-up height 4 m, sloping side 5 m.' },
    { who: 'scopey', say: 'Is it 9 × 5? The slope is the side I can see.' },
    { who: 'goldlegend', say: 'Cut the end triangle off. Slide it across.' },
    { who: 'scopey', say: 'It fits the other end! Now it is a rectangle 9 m by 4 m — the slope has gone.', add: { t: '9 × 4', v: 36 } },
    { who: 'goldlegend', say: 'A triangle flag with the same base and height is half.', add: { t: '9 × 4 ÷ 2', v: 18 } },
    { who: 'scopey', say: 'So the awning is 36 square metres. Straight-up height, never the slope.', add: { t: '9 × 4', v: 36 } },
  ] },
  'volume-cuboid': { title: 'Packing the crate', scene: 'harbour', cast: ['panda', 'samurai'], beats: [
    { who: null, say: 'At the harbour, Suki and Kwame pack cube-shaped tins into a crate 5 tins long, 3 wide and 4 tall.' },
    { who: 'samurai', say: 'Fill the bottom layer first. It is a rectangle of tins.', add: { t: '5 × 3', v: 15 } },
    { who: 'panda', say: 'Every layer is the same, and there are 4 layers.' },
    { who: 'samurai', say: 'Four layers of fifteen.', add: { t: '15 × 4', v: 60 } },
    { who: 'panda', say: 'To paint the outside we need the six faces: three pairs.', add: { t: '2 × (15 + 20 + 12)', v: 94 } },
    { who: 'samurai', say: 'Sixty tins fill it. Length times width times height.', add: { t: '5 × 3 × 4', v: 60 } },
  ] },
};
