/* The stories of coinstreet (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'fewest-coins': { title: 'The toy shop till', scene: 'shop', cast: ['pixel', 'koi'], beats: [
    { who: null, say: 'In the toy shop, a yo-yo costs 37 coins. The till has coins worth 1, 2, 5, 10, 20 and 50.', add: { t: '37' } },
    { who: 'pixel', say: 'Easy — thirty-seven 1-coins! Oh. That would take ages to count.' },
    { who: 'koi', say: 'Split it. 30 with the big coins: a 20 and a 10.', add: { t: '20 + 10', v: 30 } },
    { who: 'pixel', say: 'Then 7 with the small ones. A 5 and a 2!', add: { t: '5 + 2', v: 7 } },
    { who: 'koi', say: 'Two big coins and two small ones.', add: { t: '2 + 2', v: 4 } },
    { who: 'pixel', say: 'Four coins instead of thirty-seven. The shopkeeper will be pleased.', add: { t: '1 + 1 + 1 + 1', v: 4 } },
  ] },
  'money-left': { title: 'A day at the fair', scene: 'fair', cast: ['koi', 'comet'], beats: [
    { who: null, say: 'At the fair, Nova has 40 coins to spend. She pays 12 for the big wheel and 9 for popcorn.', add: { t: '40' } },
    { who: 'comet', say: '40 take 12 is 28, then 28 take 9 is… um… 18? 19?' },
    { who: 'koi', say: 'Add what I spent first. 12 and 9.', add: { t: '12 + 9', v: 21 } },
    { who: 'koi', say: 'Now take it away just once: 40 take 21.', add: { t: '40 − 21', v: 19 } },
    { who: 'comet', say: 'Check it the other way: 19 left plus 21 spent.', add: { t: '19 + 21', v: 40 } },
    { who: 'koi', say: '19 coins left for the rest of the fair.', add: { t: '40 − 12 − 9', v: 19 } },
  ] },
  'saving-goal': { title: 'The kite in the window', scene: 'market', cast: ['beaker', 'scopey'], beats: [
    { who: null, say: 'In the market there is a red kite for 50 coins. Rafi decides to save 6 coins a week for it.', add: { t: '50 ÷ 6' } },
    { who: 'beaker', say: 'Six eights are 48. So eight weeks.', add: { t: '6 × 8', v: 48 } },
    { who: 'scopey', say: 'Check it. After eight weeks you have 48. Does the kite cost 48?' },
    { who: 'beaker', say: 'No — I would be 2 short.', add: { t: '50 − 48', v: 2 } },
    { who: 'scopey', say: 'So one more week. Nine weeks gives you 54.', add: { t: '6 × 9', v: 54 } },
    { who: 'beaker', say: 'Nine weeks. When there is a bit left over, round UP.', add: { t: '8 + 1', v: 9 } },
  ] },
  'best-buy': { title: 'Two bags of apples', scene: 'market', cast: ['melody', 'pixel'], beats: [
    { who: null, say: 'At the fruit stall, a bag of 4 apples is 28 coins and a bag of 6 apples is 36 coins.' },
    { who: 'pixel', say: '28 is less than 36. The small bag is cheaper!' },
    { who: 'melody', say: 'It costs less, but it has fewer apples. What is ONE apple in each?', add: { t: '28 ÷ 4', v: 7 } },
    { who: 'pixel', say: 'And the big bag…', add: { t: '36 ÷ 6', v: 6 } },
    { who: 'melody', say: 'So the big bag is 1 coin cheaper for every apple.', add: { t: '7 − 6', v: 1 } },
    { who: 'pixel', say: 'The big bag, then — as long as we eat all six.', add: { t: '36 ÷ 6', v: 6 } },
  ] },
  'fraction-off': { title: 'The sale sign', scene: 'shop', cast: ['koi', 'beaker'], beats: [
    { who: null, say: 'In the sports shop, a 40-coin kite has a sign on it: 1/4 off.' },
    { who: 'beaker', say: 'Split the price into four equal parts.', add: { t: '40 ÷ 4', v: 10 } },
    { who: 'koi', say: 'One part comes off. Take it away from the price.', add: { t: '40 − 10', v: 30 } },
    { who: 'beaker', say: 'Check it another way: we pay the other three parts.', add: { t: '10 × 3', v: 30 } },
    { who: 'koi', say: 'Same answer both ways. 30 coins.', add: { t: '40 − 40 ÷ 4', v: 30 } },
  ] },
  'profit-and-loss': { title: 'The lemonade stall', scene: 'festival', cast: ['melody', 'comet'], beats: [
    { who: null, say: 'At the street festival, Dax and Ines run a lemonade stall. Lemons and sugar cost 30 coins.', add: { t: '30' } },
    { who: 'comet', say: 'We sold 14 cups at 4 coins each!', add: { t: '14 × 4', v: 56 } },
    { who: 'comet', say: 'So we made 56 coins!' },
    { who: 'melody', say: 'We took in 56. But 30 went out first, on lemons. Profit is in minus out.', add: { t: '56 − 30', v: 26 } },
    { who: 'comet', say: 'Oh. Still, 26 coins is a proper profit.' },
    { who: 'melody', say: 'And now we know what a cup costs us to make — so we can price it next time.', add: { t: '14 × 4 − 30', v: 26 } },
  ] },
  'interest-simple': { title: 'The story bank', scene: 'city', cast: ['melody', 'panda'], beats: [
    { who: null, say: 'In the city, the bank in this story pays 5% a year. Suki puts in 200 coins for 3 years.', add: { t: '200' } },
    { who: 'panda', say: 'How much does the bank pay me for that?' },
    { who: 'melody', say: 'One year is 5% of 200.', add: { t: '5% of 200', v: 10 } },
    { who: 'panda', say: 'I take the interest out each year, so every year is the same 10.' },
    { who: 'melody', say: 'Three years of it.', add: { t: '10 × 3', v: 30 } },
    { who: 'panda', say: '30 coins of interest. Simple.', add: { t: '200 × 5 × 3 ÷ 100', v: 30 } },
  ] },
  'interest-compound': { title: 'Leave it in', scene: 'city', cast: ['melody', 'samurai'], beats: [
    { who: null, say: 'Kwame puts 200 coins in the story\'s bank at 5% a year, and leaves the interest in.', add: { t: '200' } },
    { who: 'samurai', say: 'Year one: 5% of 200.', add: { t: '200 + 5% of 200', v: 210 } },
    { who: 'melody', say: 'Now the 5% is on 210, not 200.', add: { t: '5% of 210', v: 10.5 } },
    { who: 'samurai', say: 'So year two ends on…', add: { t: '210 + 10.5', v: 220.5 } },
    { who: 'melody', say: 'The extra half-coin is 5% of last year\'s interest. Interest on interest.', add: { t: '5% of 10', v: 0.5 } },
    { who: 'samurai', say: '220.50 coins. The gap grows every year it stays in.', add: { t: '200 × 1.05 × 1.05', v: 220.5 } },
  ] },
  'bill-split': { title: 'Three at the café', scene: 'kitchen', cast: ['astro', 'scopey'], beats: [
    { who: null, say: 'Mira, Theo and a friend eat at a café. Their bill is 24 + 18 + 30 coins, and the café adds 10%.', add: { t: '24 + 18 + 30', v: 72 } },
    { who: 'astro', say: 'Add the 10% to the whole bill.', add: { t: '72 + 10% of 72', v: 79.2 } },
    { who: 'scopey', say: 'Split three ways.', add: { t: '79.2 ÷ 3', v: 26.4 } },
    { who: 'astro', say: 'Check: each share was 24 before the 10%.', add: { t: '72 ÷ 3', v: 24 } },
    { who: 'scopey', say: 'And 24 plus 10% of 24 is the same.', add: { t: '24 + 10% of 24', v: 26.4 } },
    { who: 'astro', say: '26.40 each. Either order works.', add: { t: '72 × 1.1 ÷ 3', v: 26.4 } },
  ] },
  'cost-of-borrowing': { title: 'Five payments', scene: 'shop', cast: ['samurai', 'melody'], beats: [
    { who: null, say: 'In the bike shop, Kwame can borrow 100 coins for a bike and pay back 5 payments of 22 coins.', add: { t: '100' } },
    { who: 'samurai', say: '22 coins a time sounds small.' },
    { who: 'melody', say: 'Multiply it out — that is what you really pay back.', add: { t: '5 × 22', v: 110 } },
    { who: 'samurai', say: 'For a loan of 100. So the extra is…', add: { t: '110 − 100', v: 10 } },
    { who: 'melody', say: 'That is the price of borrowing. As a percentage of the loan:', add: { t: '10 ÷ 100 × 100', v: 10 } },
    { who: 'samurai', say: '10 coins to have the bike now. Now I can decide if it is worth it.', add: { t: '5 × 22 − 100', v: 10 } },
  ] },
};
