/* The stories of court (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'suanpan-add': { title: 'Beads at the stall', scene: 'market', cast: ['koi', 'pixel'], beats: [
    { who: null, say: 'Nova\'s aunt keeps a little bead abacus at her fruit stall. It shows 46 when Pip adds 7 more mangoes to the order.', add: { t: '46 + 7' } },
    { who: 'pixel', say: 'The units rod has 6. I need 7 more beads and there are not seven left!' },
    { who: 'koi', say: 'Do not add 7. Add ten and take some back. 7 and what make ten?', add: { t: '10 − 7', v: 3 } },
    { who: 'pixel', say: 'So I push one bead up on the tens rod and take 3 off the units.', add: { t: '6 − 3', v: 3 } },
    { who: 'koi', say: 'The tens rod went from 4 to 5. Read it off.', add: { t: '4 + 1', v: 5 } },
    { who: 'pixel', say: 'Fifty-three! I never added a 7 at all.', add: { t: '50 + 3', v: 53 } },
  ] },
  'suanpan-take': { title: 'Change from the till', scene: 'shop', cast: ['melody', 'comet'], beats: [
    { who: null, say: 'At the school shop, the bead counter shows 43 pencils in stock. Dax sells 8.', add: { t: '43 − 8' } },
    { who: 'comet', say: 'Three on the units rod, take eight… I cannot!' },
    { who: 'melody', say: 'Borrow one from the tens rod. The 4 becomes 3.', add: { t: '4 − 1', v: 3 } },
    { who: 'melody', say: 'That bead was worth ten. Ten take 8 leaves 2, so put 2 ON the units rod.', add: { t: '10 − 8', v: 2 } },
    { who: 'comet', say: 'Three and two: the units rod shows 5.', add: { t: '3 + 2', v: 5 } },
    { who: 'melody', say: 'Thirty-five left. Taking 8 became borrowing one and adding 2.', add: { t: '30 + 5', v: 35 } },
  ] },
  'board-multiply': { title: 'Chairs for the concert', scene: 'hall', cast: ['beaker', 'panda'], beats: [
    { who: null, say: 'Six classes each need 234 concert programmes. Rafi lays the sum out the way a counting board does.', add: { t: '234 × 6' } },
    { who: 'beaker', say: 'Biggest digit first. The 2 is two hundreds.', add: { t: '200 × 6', v: 1200 } },
    { who: 'panda', say: 'Then the 3 tens. Put it under its own place.', add: { t: '30 × 6', v: 180 } },
    { who: 'beaker', say: 'And the 4 units.', add: { t: '4 × 6', v: 24 } },
    { who: 'panda', say: 'Now add the middle row. Everything is already lined up.', add: { t: '1200 + 180 + 24', v: 1404 } },
    { who: 'beaker', say: 'One thousand four hundred and four programmes. Three small sums instead of one big one.', add: { t: '234 × 6', v: 1404 } },
  ] },
  'out-in': { title: 'The odd-shaped bed', scene: 'garden', cast: ['astro', 'scopey'], beats: [
    { who: null, say: 'The community garden has a bed shaped like a trapezium: 12 m along the bottom, 6 m along the top, 4 m from front to back.', add: { t: '12 + 6' } },
    { who: 'scopey', say: 'It is not a rectangle, so length times width is wrong. How much compost do we need to cover it?' },
    { who: 'astro', say: 'Cut it across halfway up, and turn the top half round beside the bottom half.' },
    { who: 'astro', say: 'Now the top and bottom lie end to end.', add: { t: '12 + 6', v: 18 } },
    { who: 'scopey', say: 'And it is only half as tall.', add: { t: '4 ÷ 2', v: 2 } },
    { who: 'astro', say: 'A rectangle we can measure. Nothing was added, nothing lost.', add: { t: '18 × 2', v: 36 } },
  ] },
  'red-black-rods': { title: 'Gains and debts', scene: 'room', cast: ['samurai', 'pixel'], beats: [
    { who: null, say: 'Kwame keeps score in a board game with red sticks for points won and black sticks for points owed. Pip has 7 red, then a card says: take away 12 red.' },
    { who: 'pixel', say: 'I only have 7. I cannot take 12 away!' },
    { who: 'samurai', say: 'Same colours, taking away: take what you can. You are short by this many.', add: { t: '12 − 7', v: 5 } },
    { who: 'samurai', say: 'The shortfall shows in the other colour. You owe 5 — five black sticks.' },
    { who: 'pixel', say: 'So my score is negative five.', add: { t: '7 − 12', v: -5 } },
    { who: 'samurai', say: 'Next a card takes 3 black sticks away. Same colour again: 3 of your 5 debts vanish, and you still owe 2.', add: { t: '-5 − (-3)', v: -2 } },
  ] },
  'excess-deficit': { title: 'Clubbing together', scene: 'festival', cast: ['melody', 'goldlegend'], beats: [
    { who: null, say: 'Friends are buying a present. If each pays 8 coins, there are 3 too many. If each pays 7, they are 4 short.' },
    { who: 'melody', say: 'We do not even know how many friends there are. Or the price.' },
    { who: 'goldlegend', say: 'The two collections are this far apart.', add: { t: '3 + 4', v: 7 } },
    { who: 'goldlegend', say: 'And going from 7 each to 8 each adds one coin per person.', add: { t: '8 − 7', v: 1 } },
    { who: 'melody', say: 'So the friends are the gap divided by one coin each.', add: { t: '7 ÷ 1', v: 7 } },
    { who: 'goldlegend', say: 'Seven friends pay 8 each, less the 3 too many: that is the price.', add: { t: '7 × 8 − 3', v: 53 } },
  ] },
  'fangcheng': { title: 'Two heavy bags', scene: 'kitchen', cast: ['samurai', 'koi'], beats: [
    { who: null, say: 'In the kitchen, 3 bags of rice and 2 of lentils weigh 29 kg. Another shelf has 2 of rice and 3 of lentils, 26 kg.' },
    { who: 'koi', say: 'Two kinds of bag in every fact. How do we get one alone?' },
    { who: 'samurai', say: 'Write each fact as a column. Make the second shelf three times as big — still true.', add: { t: '26 × 3', v: 78 } },
    { who: 'samurai', say: 'Take the first shelf away twice. The rice disappears, and the lentils are this many bags.', add: { t: '3 × 3 − 2 × 2', v: 5 } },
    { who: 'koi', say: 'And the kilograms left over.', add: { t: '78 − 2 × 29', v: 20 } },
    { who: 'koi', say: 'Five bags of lentils weigh 20 kg, so one weighs…', add: { t: '20 ÷ 5', v: 4 } },
  ] },
  'sunzi-multipliers': { title: 'The cupcake boxes', scene: 'bakery', cast: ['beaker', 'astro'], beats: [
    { who: null, say: 'At a bake sale, cupcakes packed in threes leave 2 over, and packed in sevens leave 4 over. Rafi wants the smallest number there could be.' },
    { who: 'beaker', say: 'First a multiple of 7 that leaves 1 by threes. Seven itself does.', add: { t: '7 − 6', v: 1 } },
    { who: 'astro', say: 'Then a multiple of 3 that leaves 1 by sevens. 15 works.', add: { t: '15 − 14', v: 1 } },
    { who: 'beaker', say: 'Two lots of the first, four of the second.', add: { t: '2 × 7 + 4 × 15', v: 74 } },
    { who: 'astro', say: 'Taking away 21 changes neither leftover. Take it away three times.', add: { t: '74 − 3 × 21', v: 11 } },
    { who: 'beaker', say: 'Eleven cupcakes: 3 threes and 2 over, 1 seven and 4 over.', add: { t: '3 × 3 + 2', v: 11 } },
  ] },
  'sea-island': { title: 'The rock in the lake', scene: 'pond', cast: ['scopey', 'astro'], beats: [
    { who: null, say: 'There is a tall rock on an island in the park lake. Theo and Mira set up two 5 m poles 60 m apart, in line with the rock.' },
    { who: 'scopey', say: 'Lying down, I see the top of the rock over the first pole from 6 m back. Behind the second pole I need 9 m.' },
    { who: 'astro', say: 'You went back this much further the second time.', add: { t: '9 − 6', v: 3 } },
    { who: 'astro', say: 'It fits into the 60 m between the poles this many times.', add: { t: '60 ÷ 3', v: 20 } },
    { who: 'scopey', say: 'So the rock rises twenty pole-heights above the pole tops.', add: { t: '20 × 5', v: 100 } },
    { who: 'astro', say: 'Add the pole itself. Similar triangles, and nobody got wet.', add: { t: '100 + 5', v: 105 } },
  ] },
  'liu-hui': { title: 'The round table', scene: 'room', cast: ['astro', 'comet'], beats: [
    { who: null, say: 'Mira draws a hexagon inside a round table top of radius 10 cm on paper, and Dax wants to know how close it gets to the circle.' },
    { who: 'comet', say: 'Each side is a radius — six equilateral triangles.', add: { t: '6 × 10', v: 60 } },
    { who: 'astro', say: 'Perimeter over diameter. That says π is 3. Too small.', add: { t: '60 ÷ 20', v: 3 } },
    { who: 'comet', say: 'Put a corner between each pair: 12 sides, each about 5.18 cm.', add: { t: '12 × 5.18', v: 62.16 } },
    { who: 'astro', say: 'Over the diameter again. Closer already.', add: { t: '62.16 ÷ 20', v: 3.108 } },
    { who: 'comet', say: 'Double again: 24 sides of about 2.61 cm each.', add: { t: '24 × 2.61', v: 62.64 } },
    { who: 'astro', say: 'Closer still, and still just under the circle. Keep doubling and it creeps towards 3.14.', add: { t: '62.64 ÷ 20', v: 3.132 } },
  ] },
  'hundred-fowls': { title: 'The farm sale', scene: 'fair', cast: ['panda', 'samurai'], beats: [
    { who: null, say: 'At a farm sale: roosters 5 coins, hens 3, chicks 3 for a coin. Suki must buy 100 birds for exactly 100 coins, with as many roosters as possible.' },
    { who: 'panda', say: 'Three kinds of bird and only two facts. That is not enough.' },
    { who: 'samurai', say: 'Triple the coins, then take away the birds. The chicks vanish.', add: { t: '100 × 3 − 100', v: 200 } },
    { who: 'samurai', say: 'Fourteen for each rooster, eight for each hen. The answers step along: 4 roosters, 8, 12…' },
    { who: 'panda', say: 'As many roosters as possible: 12. Then the hens.', add: { t: '(200 − 14 × 12) ÷ 8', v: 4 } },
    { who: 'samurai', say: 'And the chicks make up the hundred. Check: 60 + 12 + 28 coins.', add: { t: '100 − 12 − 4', v: 84 } },
  ] },
};
