/* The stories of dock (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'decimal-places': { title: 'The ribbon stall', scene: 'market', cast: ['beaker', 'pixel'], beats: [
    { who: null, say: 'At the market, Pip buys 3.47 metres of blue ribbon for a kite tail.', add: { t: '3.47' } },
    { who: 'pixel', say: 'The 7 is the biggest digit after the point, so it must be worth the most.' },
    { who: 'beaker', say: 'Take it apart. Before the point: 3 whole metres.', add: { t: '3', v: 3 } },
    { who: 'beaker', say: 'First place after the point is tenths: 4 tenths of a metre.', add: { t: '4 ÷ 10', v: 0.4 } },
    { who: 'beaker', say: 'Second place is hundredths. The 7 is only 7 hundredths — a few centimetres.', add: { t: '7 ÷ 100', v: 0.07 } },
    { who: 'pixel', say: 'So the place matters more than the digit. 347 hundredths of a metre in all.', add: { t: '347 ÷ 100', v: 3.47 } },
  ] },
  'times-ten-decimals': { title: 'A hundred tickets', scene: 'harbour', cast: ['samurai', 'comet'], beats: [
    { who: null, say: 'A ferry ticket costs 2.35 coins. The school needs 100 tickets.', add: { t: '2.35 × 100' } },
    { who: 'comet', say: 'Put two zeros on the end! 2.3500.' },
    { who: 'samurai', say: 'That does not change anything — 2.3500 is still 2.35. Zeros after the point add nothing.' },
    { who: 'samurai', say: 'Times 100 makes every digit worth a hundred times more. Slide them two places left.' },
    { who: 'comet', say: 'The 2 goes to the hundreds, 3 to the tens, 5 to the ones: 235.', add: { t: '2.35 × 100', v: 235 } },
    { who: 'samurai', say: 'And back again: slide them two places right.', add: { t: '235 ÷ 100', v: 2.35 } },
  ] },
  'add-decimals': { title: 'Two bags of shopping', scene: 'shop', cast: ['scopey', 'koi'], beats: [
    { who: null, say: 'Nova buys bread for 3.5 coins and cheese for 1.27 coins.', add: { t: '3.5 + 1.27' } },
    { who: 'koi', say: 'Five and twenty-seven is thirty-two… so 1.62?' },
    { who: 'scopey', say: 'That cannot be right — the bread alone is more than 3. Line up the points.' },
    { who: 'scopey', say: 'In hundredths, 3.5 is 350 and 1.27 is 127.', add: { t: '350 + 127', v: 477 } },
    { who: 'koi', say: '477 hundredths. Back to coins…', add: { t: '477 ÷ 100', v: 4.77 } },
    { who: 'scopey', say: '4.77 coins. Tenths under tenths, every time.', add: { t: '3.5 + 1.27', v: 4.77 } },
  ] },
  'round-decimals': { title: 'The longest fish', scene: 'beach', cast: ['panda', 'comet'], beats: [
    { who: null, say: 'On the beach, Dax measures a piece of driftwood: 12.68 metres of rope would go round it.', add: { t: '12.68' } },
    { who: 'comet', say: 'Nobody wants two decimal places. What is it to one?' },
    { who: 'panda', say: 'Cut it after the first decimal place. That gives 12.6.', add: { t: '12.6', v: 12.6 } },
    { who: 'panda', say: 'Now the very next digit decides. It is 8 — well past halfway to 12.7.' },
    { who: 'comet', say: 'Five or more goes up. So about 12.7 metres.', add: { t: '12.6 + 0.1', v: 12.7 } },
    { who: 'panda', say: 'And to the nearest whole metre, the 6 decides: 13.', add: { t: '12 + 1', v: 13 } },
  ] },
  'fraction-decimal-percent': { title: 'Three signs, one discount', scene: 'shop', cast: ['melody', 'pixel'], beats: [
    { who: null, say: 'Three shops on the high street. One sign says 3/4 of the price. One says 0.75 of the price. One says 75%.' },
    { who: 'pixel', say: 'Which is the best deal?' },
    { who: 'melody', say: 'Turn 3/4 into hundredths. 4 goes into 100 this many times…', add: { t: '100 ÷ 4', v: 25 } },
    { who: 'melody', say: '…so 3 quarters is 75 hundredths.', add: { t: '3 × 25', v: 75 } },
    { who: 'pixel', say: '75 hundredths is 0.75. And per cent means hundredths, so it is 75%!', add: { t: '75 ÷ 100', v: 0.75 } },
    { who: 'melody', say: 'Three signs, one number. Pick the shop with the nicest cake.', add: { t: '3/4', v: 0.75 } },
  ] },
  'percent-of-amount': { title: 'The harbour tax', scene: 'harbour', cast: ['melody', 'beaker'], beats: [
    { who: null, say: 'The fishing boat brought in 60 kg of fish. 35% goes to the market in town.', add: { t: '35% of 60' } },
    { who: 'beaker', say: 'Thirty-five per cent. I only know how to do ten.' },
    { who: 'melody', say: 'Then start there. 10% is a tenth.', add: { t: '60 ÷ 10', v: 6 } },
    { who: 'beaker', say: '30% is three of those.', add: { t: '6 × 3', v: 18 } },
    { who: 'melody', say: '5% is half of 10%.', add: { t: '6 ÷ 2', v: 3 } },
    { who: 'beaker', say: 'Add them up: 21 kg to the market.', add: { t: '35% of 60', v: 21 } },
  ] },
  'unitary-method': { title: 'Pancakes for six', scene: 'kitchen', cast: ['koi', 'panda'], beats: [
    { who: null, say: 'The recipe makes 4 pancakes with 200 g of flour. Six people are coming for breakfast.', add: { t: '200' } },
    { who: 'koi', say: 'Four to six is not a doubling. How do I scale it?' },
    { who: 'panda', say: 'Go to one pancake first.', add: { t: '200 ÷ 4', v: 50 } },
    { who: 'koi', say: '50 g for each pancake. Then six of them…', add: { t: '50 × 6', v: 300 } },
    { who: 'panda', say: 'Find one, then scale. It works for the eggs and the milk too.' },
    { who: 'koi', say: '300 g of flour for six pancakes.', add: { t: '200 ÷ 4 × 6', v: 300 } },
  ] },
  'percent-change': { title: 'The jacket sale', scene: 'shop', cast: ['melody', 'comet'], beats: [
    { who: null, say: 'A jacket costs 60 coins. The sign says 20% off.', add: { t: '20% of 60' } },
    { who: 'comet', say: 'Twenty off — so 40 coins!' },
    { who: 'melody', say: 'Twenty PER CENT, not twenty coins. 20% of 60 is…', add: { t: '20% of 60', v: 12 } },
    { who: 'comet', say: 'Twelve off. So I pay…', add: { t: '60 − 12', v: 48 } },
    { who: 'melody', say: 'Or skip a step: if 20% is taken off, you pay 80%.', add: { t: '80% of 60', v: 48 } },
    { who: 'comet', say: '48 coins, both ways.' },
  ] },
  'ratio-share': { title: 'The mango crate', scene: 'market', cast: ['beaker', 'panda'], beats: [
    { who: null, say: 'Suki and Rafi fill a crate with 35 mangoes. Rafi picked 2 for every 5 Suki picked, so they share it 2 : 5.', add: { t: '35' } },
    { who: 'beaker', say: 'Hand them out in rounds: 2 for me, 5 for you. Each round uses…', add: { t: '2 + 5', v: 7 } },
    { who: 'panda', say: 'How many rounds in 35?', add: { t: '35 ÷ 7', v: 5 } },
    { who: 'beaker', say: 'Five rounds of 2 for me.', add: { t: '5 × 2', v: 10 } },
    { who: 'panda', say: 'Five rounds of 5 for me.', add: { t: '5 × 5', v: 25 } },
    { who: 'beaker', say: 'And 10 + 25 is all 35. Nothing left in the crate.', add: { t: '10 + 25', v: 35 } },
  ] },
  'speed-distance-time': { title: 'The coast train', scene: 'train', cast: ['astro', 'scopey'], beats: [
    { who: null, say: 'Mira and Theo take the train to the coast: 240 km, and the train runs at 80 km/h.', add: { t: '240 ÷ 80' } },
    { who: 'scopey', say: 'How long will it take? We have to catch the ferry.' },
    { who: 'astro', say: '80 km/h means 80 km in every hour. One hour, two hours…', add: { t: '80 × 2', v: 160 } },
    { who: 'astro', say: 'Three hours gets us all the way.', add: { t: '80 × 3', v: 240 } },
    { who: 'scopey', say: 'So time is distance divided by speed.', add: { t: '240 ÷ 80', v: 3 } },
    { who: 'astro', say: 'Three hours. Time for a sandwich.' },
  ] },
};
