/* The stories of figures (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'count-triangles': { title: 'The bunting puzzle', scene: 'fair', cast: ['pixel', 'beaker'], beats: [
    { who: null, say: 'At the fair, a big wooden triangle hangs over the gate. Strings run from its top corner to 5 points along the bottom bar.' },
    { who: 'pixel', say: 'I can see four little triangles. Four!' },
    { who: 'beaker', say: 'Those are just the thin ones. Two strings next-but-one make a fatter triangle too. Every triangle uses the top and two strings.' },
    { who: 'pixel', say: 'So I count the pairs of strings? The first string pairs with four others…', add: { t: '4 + 3 + 2 + 1', v: 10 } },
    { who: 'beaker', say: 'Or count from every string and halve, because each pair got counted from both ends.', add: { t: '5 × 4 ÷ 2', v: 10 } },
    { who: 'pixel', say: 'Ten triangles over the gate — and I only saw four.', add: { t: '5 × 4 ÷ 2', v: 10 } },
  ] },
  'count-rectangles': { title: 'The chocolate bar', scene: 'kitchen', cast: ['koi', 'astro'], beats: [
    { who: null, say: 'Mira breaks open a chocolate bar 4 pieces wide and 3 pieces tall. Nova bets her there are only twelve rectangles in it.', add: { t: '4 × 3', v: 12 } },
    { who: 'astro', say: 'Twelve is just the little pieces. A row of two is a rectangle. So is the whole bar.' },
    { who: 'koi', say: 'Then how do you count them all without missing one?' },
    { who: 'astro', say: 'Look at the grooves. A rectangle picks two of the 5 upright lines for its sides.', add: { t: '5 × 4 ÷ 2', v: 10 } },
    { who: 'koi', say: 'And two of the 4 across lines for its top and bottom.', add: { t: '4 × 3 ÷ 2', v: 6 } },
    { who: 'astro', say: 'Every choice of sides goes with every choice of top and bottom.', add: { t: '10 × 6', v: 60 } },
    { who: 'koi', say: 'Sixty rectangles in one bar. I owe you a piece.', add: { t: '10 × 6', v: 60 } },
  ] },
  'handshakes': { title: 'The first day of the club', scene: 'hall', cast: ['comet', 'panda'], beats: [
    { who: null, say: 'Ten new members meet in the hall for the maths club, and everyone shakes hands with everyone else once.', add: { t: '10' } },
    { who: 'comet', say: 'Ten people, nine handshakes each — ninety! My hand will fall off.', add: { t: '10 × 9', v: 90 } },
    { who: 'panda', say: 'When you shake my hand, you count it and I count it. That is one handshake counted twice.' },
    { who: 'comet', say: 'Oh. So every handshake is in the ninety two times.' },
    { who: 'panda', say: 'Halve it.', add: { t: '90 ÷ 2', v: 45 } },
    { who: 'comet', say: 'Forty-five handshakes. Still a lot, but my hand will live.', add: { t: '10 × 9 ÷ 2', v: 45 } },
  ] },
  'grid-paths': { title: 'Through the market', scene: 'market', cast: ['scopey', 'pixel'], beats: [
    { who: null, say: 'The market is laid out in squares, 4 across and 3 up. Pip wants to get from the bottom-left stall to the top-right one, going only right or up.' },
    { who: 'pixel', say: 'I will just try every route. Right, right, up… no, wait, I did that one.' },
    { who: 'scopey', say: 'Count arrivals instead. Every stall on the bottom row and the left side can only be reached one way.', add: { t: '1' } },
    { who: 'pixel', say: 'And the stall next to those can be reached from the left or from below.', add: { t: '1 + 1', v: 2 } },
    { who: 'scopey', say: 'Fill them all in that way. The end stall gets the stall to its left plus the one below it.', add: { t: '4 + 6', v: 10 } },
    { who: 'pixel', say: 'Ten routes, and I never had to draw one.', add: { t: '4 + 6', v: 10 } },
  ] },
  'overlapping-groups': { title: 'Pets in the class', scene: 'room', cast: ['melody', 'koi'], beats: [
    { who: null, say: 'In a class of 30, 18 children have a cat, 15 have a dog, and 5 have neither.', add: { t: '18 + 15', v: 33 } },
    { who: 'koi', say: 'That is 33 with a pet — but there are only 30 in the whole class!' },
    { who: 'melody', say: 'The children with both a cat and a dog were counted twice. Add the 5 with no pet too.', add: { t: '33 + 5', v: 38 } },
    { who: 'koi', say: 'Thirty-eight counts for thirty children. So eight of them were counted twice.', add: { t: '38 − 30', v: 8 } },
    { who: 'melody', say: 'Eight have both. Check: cat or dog is 18 + 15 − 8.', add: { t: '18 + 15 − 8', v: 25 } },
    { who: 'koi', say: 'And 25 with a pet plus 5 without is the whole class. Eight have both.', add: { t: '38 − 30', v: 8 } },
  ] },
  'staircase-perimeter': { title: 'The garden steps', scene: 'garden', cast: ['astro', 'comet'], beats: [
    { who: null, say: 'A flower bed is cut like a staircase, 9 metres wide and 7 metres tall. Dax needs edging all the way round it.', add: { t: '9 + 7', v: 16 } },
    { who: 'comet', say: 'But the steps are all different sizes and nobody measured them!' },
    { who: 'astro', say: 'Slide every little across-piece up to the top. Together they are as long as the bottom.', add: { t: '9 × 2', v: 18 } },
    { who: 'comet', say: 'And the little up-pieces slide across to match the left side.', add: { t: '7 × 2', v: 14 } },
    { who: 'astro', say: 'So the edging is the same as for a 9 by 7 rectangle.', add: { t: '18 + 14', v: 32 } },
    { who: 'comet', say: 'Thirty-two metres of edging — and I never measured a single step.', add: { t: '2 × (9 + 7)', v: 32 } },
  ] },
  'area-cut-and-move': { title: 'The kite design', scene: 'festival', cast: ['beaker', 'melody'], beats: [
    { who: null, say: 'Rafi draws a kite for the festival on squared paper. It covers 6 whole squares and 8 half squares cut by diagonals.' },
    { who: 'melody', say: 'Half squares are awkward. How much paper does it need?' },
    { who: 'beaker', say: 'Cut and move. Two half squares slide together into one whole square.', add: { t: '8 ÷ 2', v: 4 } },
    { who: 'melody', say: 'So the eight halves are worth four whole squares.' },
    { who: 'beaker', say: 'Add the whole squares that were there already.', add: { t: '6 + 4', v: 10 } },
    { who: 'melody', say: 'Ten squares of paper for the kite.', add: { t: '6 + 8 ÷ 2', v: 10 } },
  ] },
  'dice-faces': { title: 'The dice tower', scene: 'room', cast: ['goldlegend', 'pixel'], beats: [
    { who: null, say: 'Pip builds a tower of 4 dice on the table. The top face shows 3. Vesper asks how many dots are hidden.' },
    { who: 'pixel', say: 'How could anyone know? I cannot see underneath.' },
    { who: 'goldlegend', say: 'Opposite faces of a dice always make 7.', add: { t: '1 + 6', v: 7 } },
    { who: 'pixel', say: 'So each dice has 7 on its top and bottom, however it is turned.', add: { t: '4 × 7', v: 28 } },
    { who: 'goldlegend', say: 'All of those are hidden, except the one top face you can see.' },
    { who: 'pixel', say: 'Twenty-eight take away three. Twenty-five hidden dots!', add: { t: '28 − 3', v: 25 } },
  ] },
  'angle-chasing': { title: 'The tent poles', scene: 'festival', cast: ['samurai', 'scopey'], beats: [
    { who: null, say: 'A festival tent is shaped like a triangle with two equal sloping sides. The angle at the top is 40°.', add: { t: '40' } },
    { who: 'scopey', say: 'What angle do the poles make with the ground? We have no protractor.' },
    { who: 'samurai', say: 'The three angles of a triangle make 180°. Take away the top.', add: { t: '180 − 40', v: 140 } },
    { who: 'scopey', say: 'The two sides are equal, so the two bottom angles are equal too.' },
    { who: 'samurai', say: 'Share the 140 between them.', add: { t: '140 ÷ 2', v: 70 } },
    { who: 'scopey', say: 'Check: 70 + 70 + 40 is 180. Each pole meets the ground at 70°.', add: { t: '(180 − 40) ÷ 2', v: 70 } },
  ] },
  'painted-cubes': { title: 'The red cube', scene: 'shop', cast: ['panda', 'beaker'], beats: [
    { who: null, say: 'A toy shop paints a big wooden cube red, then saws it into little cubes, 4 along every edge.', add: { t: '4 × 4 × 4', v: 64 } },
    { who: 'beaker', say: 'How many little cubes have red on exactly two faces?' },
    { who: 'panda', say: 'Two red faces means it sat on an edge — but not at a corner, because corners have three.' },
    { who: 'beaker', say: 'Each edge has 4 cubes. Leave out the 2 corners.', add: { t: '4 − 2', v: 2 } },
    { who: 'panda', say: 'And a cube has 12 edges.', add: { t: '12 × 2', v: 24 } },
    { who: 'beaker', say: 'Twenty-four little cubes with two red faces.', add: { t: '12 × (4 − 2)', v: 24 } },
  ] },
};
