/* The stories of forest (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'factor-pairs': { title: 'Planting the orchard', scene: 'forest', cast: ['astro', 'pixel'], beats: [
    { who: null, say: 'The forest club has 36 saplings to plant in a neat rectangle. How many different rectangles could they make?' },
    { who: 'pixel', say: 'One long row of 36! Or 2 rows of 18…', add: { t: '2 × 18', v: 36 } },
    { who: 'astro', say: 'Keep going: 3 rows of 12, 4 rows of 9…', add: { t: '4 × 9', v: 36 } },
    { who: 'pixel', say: '5 rows doesn’t work. 6 rows of 6 — a square!', add: { t: '6 × 6', v: 36 } },
    { who: 'astro', say: 'Stop there. 7 rows would need fewer than 6 in a row, and we’ve met all of those already.' },
    { who: 'astro', say: 'Five pairs, but 6 × 6 is one number twice. So 36 has nine factors.', add: { t: '5 × 2 − 1', v: 9 } },
  ] },
  'multiples': { title: 'Boxes of eggs', scene: 'market', cast: ['koi', 'comet'], beats: [
    { who: null, say: 'Nova’s class needs more than 50 eggs for the baking day. Eggs come in boxes of 6.', add: { t: '50 ÷ 6' } },
    { who: 'comet', say: 'Six, twelve, eighteen… this will take ages.' },
    { who: 'koi', say: 'How many whole boxes fit in 50? Eight boxes is 48.', add: { t: '8 × 6', v: 48 } },
    { who: 'comet', say: 'That’s not more than 50, though.' },
    { who: 'koi', say: 'So one box more.', add: { t: '8 + 1', v: 9 } },
    { who: 'comet', say: 'Nine boxes: 54 eggs. The first multiple of 6 over 50.', add: { t: '9 × 6', v: 54 } },
  ] },
  'divisible-2-5-10': { title: 'Bracelets of five', scene: 'room', cast: ['melody', 'pixel'], beats: [
    { who: null, say: 'Pip has 3,475 beads, and wants to thread every one onto bracelets of 5 beads each.', add: { t: '3,475' } },
    { who: 'pixel', say: 'Will there be any left over? I’d have to divide the whole thing by 5.' },
    { who: 'melody', say: 'No need. 3,470 is a pile of tens, and every ten is two fives.', add: { t: '3470 ÷ 5', v: 694 } },
    { who: 'melody', say: 'So only the last digit matters. It’s a 5.' },
    { who: 'pixel', say: 'So none left over!', add: { t: '3475 ÷ 5', v: 695 } },
    { who: 'melody', say: 'Last digit 0 or 5: yes for five. Even: yes for two. A 0: yes for ten.' },
  ] },
  'divisible-4-8': { title: 'The seed packets', scene: 'garden', cast: ['beaker', 'panda'], beats: [
    { who: null, say: 'The seed library has 73,516 seeds to share into packets of 4.' },
    { who: 'beaker', say: 'Every hundred splits into four 25s, so all the hundreds are fine.', add: { t: '100 ÷ 4', v: 25 } },
    { who: 'panda', say: 'Then only the last two digits matter: 16.' },
    { who: 'beaker', say: '16 is four fours. So yes, it splits exactly.', add: { t: '16 ÷ 4', v: 4 } },
    { who: 'panda', say: 'For 8 you’d need the last three digits — 1000 is eight 125s.', add: { t: '1000 ÷ 8', v: 125 } },
    { who: 'beaker', say: 'And 73,516 in packets of 4 makes…', add: { t: '73516 ÷ 4', v: 18379 } },
  ] },
  'divisible-6-11': { title: 'Teams of eleven', scene: 'stadium', cast: ['samurai', 'comet'], beats: [
    { who: null, say: '4,158 children sign up for the district football festival. Can they make teams of exactly 11?' },
    { who: 'comet', say: 'I’ll do the long division…' },
    { who: 'samurai', say: 'Faster: from the right, add every other digit. 8 and 1.', add: { t: '8 + 1', v: 9 } },
    { who: 'samurai', say: 'Now the ones you skipped: 5 and 4.', add: { t: '5 + 4', v: 9 } },
    { who: 'comet', say: 'Nine take nine is zero!', add: { t: '9 − 9', v: 0 } },
    { who: 'samurai', say: 'A difference of 0 means 11 divides it.', add: { t: '4158 ÷ 11', v: 378 } },
  ] },
  'prime-or-not': { title: 'The sieve', scene: 'night', cast: ['goldlegend', 'scopey'], beats: [
    { who: null, say: 'On a camping night, Theo asks Vesper: is 91 prime? It is odd, it does not end in 5, and its digits add to 10.', add: { t: '9 + 1', v: 10 } },
    { who: 'scopey', say: 'So not 2, not 3, not 5. I think it’s prime.' },
    { who: 'goldlegend', say: 'Try 7.' },
    { who: 'scopey', say: 'Seven thirteens… that’s 91!', add: { t: '7 × 13', v: 91 } },
    { who: 'goldlegend', say: 'You only had to try up to 9, because 10 times 10 is already past it.', add: { t: '10 × 10', v: 100 } },
    { who: 'scopey', say: 'Next time I’ll try every prime up to there, and check them all.' },
  ] },
  'factor-tree': { title: 'The family tree of 84', scene: 'forest', cast: ['beaker', 'koi'], beats: [
    { who: null, say: 'Rafi carves 84 at the top of a trail sign and draws two branches under it.', add: { t: '84' } },
    { who: 'beaker', say: '84 is even, so one branch is 2.', add: { t: '84 ÷ 2', v: 42 } },
    { who: 'koi', say: '42 is even too: another 2.', add: { t: '42 ÷ 2', v: 21 } },
    { who: 'beaker', say: '21 is 3 times 7, and both of those are prime, so the branches stop.', add: { t: '21 ÷ 3', v: 7 } },
    { who: 'koi', say: 'Check: multiply all the ends back together.', add: { t: '2 × 2 × 3 × 7', v: 84 } },
    { who: 'beaker', say: 'Split it any way you like — the ends are always 2, 2, 3 and 7.' },
  ] },
  'hcf': { title: 'Sharing the fruit', scene: 'kitchen', cast: ['melody', 'panda'], beats: [
    { who: null, say: 'Ines has 24 oranges and 36 apples to pack into identical bags, with nothing left over. What is the most bags she can fill?' },
    { who: 'panda', say: 'Both are even. Halve both.', add: { t: '24 ÷ 2', v: 12 } },
    { who: 'melody', say: '12 and 18. Still both even. Halve again: 6 and 9.', add: { t: '12 ÷ 2', v: 6 } },
    { who: 'panda', say: '6 and 9 are both in the three times table: 2 and 3.', add: { t: '6 ÷ 3', v: 2 } },
    { who: 'melody', say: 'Nothing divides 2 and 3 both. So I took out 2, 2 and 3.', add: { t: '2 × 2 × 3', v: 12 } },
    { who: 'panda', say: 'Twelve bags, each with 2 oranges and 3 apples.' },
  ] },
  'lcm': { title: 'The two buses', scene: 'bus', cast: ['scopey', 'pixel'], beats: [
    { who: null, say: 'The number 6 bus comes every 6 minutes and the number 8 bus every 8. Both have just left the stop.' },
    { who: 'pixel', say: 'They’ll meet again in 48 minutes — six times eight!', add: { t: '6 × 8', v: 48 } },
    { who: 'scopey', say: 'Check the lists. The 6 bus: 6, 12, 18, 24. The 8 bus: 8, 16, 24.' },
    { who: 'pixel', say: '24 is in both! So 48 was too late?' },
    { who: 'scopey', say: '6 and 8 share a factor of 2, so multiplying counts it twice. Take it out once.', add: { t: '48 ÷ 2', v: 24 } },
    { who: 'pixel', say: 'Or 6 ÷ 2, then times 8 — smaller numbers.', add: { t: '6 ÷ 2 × 8', v: 24 } },
  ] },
};
