/* The stories of ladder (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'nine-division': { title: 'Lamps in boxes of nine', scene: 'festival', cast: ['koi', 'pixel'], beats: [
    { who: null, say: 'The festival committee has 1232 clay lamps to pack in boxes of 9. How many full boxes, and how many lamps left over?', add: { t: '1232 ÷ 9' } },
    { who: 'pixel', say: 'Nine times WHAT is 1232? I’ll be guessing all night!' },
    { who: 'koi', say: 'Running totals of the digits instead: 1, then 1 + 2, then 3 + 3.', add: { t: '1 + 2 + 3', v: 6 } },
    { who: 'pixel', say: 'And all four digits add to 8. Is that the lamps left over?', add: { t: '1 + 2 + 3 + 2', v: 8 } },
    { who: 'koi', say: 'Yes — 8 is less than 9, so nothing moves. Check: 136 boxes of 9, plus 8.', add: { t: '136 × 9 + 8', v: 1232 } },
    { who: 'pixel', say: 'So the totals 1, 3, 6 read as 136 full boxes, with 8 lamps over.', add: { t: '(1232 − 8) ÷ 9', v: 136 } },
  ] },
  'base-division': { title: 'Carriages of ninety-eight', scene: 'train', cast: ['melody', 'samurai'], beats: [
    { who: null, say: 'The hill train has carriages of 98 seats, and 2391 people are booked. How many carriages are completely full?', add: { t: '2391 ÷ 98' } },
    { who: 'melody', say: 'What an awkward number. 98 does not go into anything nicely.' },
    { who: 'samurai', say: '98 is 2 short of 100. Every hundred people fill one carriage and leave 2 standing. 23 hundreds leave 46.', add: { t: '23 × 2', v: 46 } },
    { who: 'melody', say: 'Plus the 91 on the end of 2391 — that is 137 people still standing.', add: { t: '46 + 91', v: 137 } },
    { who: 'samurai', say: '137 fills one more carriage of 98, with 39 left over.', add: { t: '137 − 98', v: 39 } },
    { who: 'melody', say: 'So 24 full carriages, and 39 people in the last one.', add: { t: '(2391 − 39) ÷ 98', v: 24 } },
  ] },
  'ekadhika-decimals': { title: 'The digits of one nineteenth', scene: 'night', cast: ['beaker', 'scopey'], beats: [
    { who: null, say: 'Under the stars, Rafi wants the digits of 1 ÷ 19. Theo’s calculator screen is too short to show them all.', add: { t: '1 ÷ 19' } },
    { who: 'beaker', say: 'One more than the 1 in 19 is 2. So I only ever divide by 2. 1 ÷ 2 is 0, remainder 1.' },
    { who: 'beaker', say: 'The remainder goes in front of the 0: 10 ÷ 2 is 5, remainder 0.', add: { t: '10 ÷ 2', v: 5 } },
    { who: 'scopey', say: 'Remainder 0 in front of the 5 is just 5. 5 ÷ 2 is 2, remainder 1.', add: { t: '(5 − 1) ÷ 2', v: 2 } },
    { who: 'scopey', say: 'Let me check what we have: 19 × 526 should be just under 10000.', add: { t: '19 × 526', v: 9994 } },
    { who: 'beaker', say: 'Remainder 1 in front of the 2 is 12, and 12 ÷ 2 is 6. The fourth digit is 6.', add: { t: '12 ÷ 2', v: 6 } },
  ] },
  'flag-division': { title: 'Rows of twenty-three', scene: 'stadium', cast: ['comet', 'panda'], beats: [
    { who: null, say: 'The stadium has 1748 seats in rows of 23. How many rows are there?', add: { t: '1748 ÷ 23' } },
    { who: 'comet', say: 'Easy! 23 times 80 is… no. 23 times 70 is… hang on.' },
    { who: 'panda', say: 'Divide by the 2 only, and fly the 3 as a flag. 17 ÷ 2 is 8 — but then the next column goes below zero. So 7, remainder 3.' },
    { who: 'panda', say: 'The 3 goes in front of the 4: 34. Take off flag × 7.', add: { t: '34 − 3 × 7', v: 13 } },
    { who: 'comet', say: '13 ÷ 2 is 6, remainder 1. Then 18, take off 3 × 6 — that is zero!', add: { t: '18 − 3 × 6', v: 0 } },
    { who: 'panda', say: 'Nothing left over. 76 rows.', add: { t: '1748 ÷ 23', v: 76 } },
  ] },
  'duplex': { title: 'The giant mosaic', scene: 'room', cast: ['astro', 'beaker'], beats: [
    { who: null, say: 'A square mosaic for the town hall will be 473 tiles wide and 473 tall. How many tiles must be ordered?', add: { t: '473 × 473' } },
    { who: 'astro', say: 'A square is duplexes, column by column. The duplex of 4 is 16, and of 47 it is twice 4 × 7.', add: { t: '2 × 4 × 7', v: 56 } },
    { who: 'beaker', say: 'The duplex of 473: twice the outer pair, plus the middle squared.', add: { t: '2 × 4 × 3 + 7 × 7', v: 73 } },
    { who: 'astro', say: 'Then 73 gives twice 7 × 3, and 3 gives 9. The columns are 16, 56, 73, 42, 9.', add: { t: '2 × 7 × 3', v: 42 } },
    { who: 'beaker', say: 'Carry from the right: 9; 2 carry 4; 7 carry 7; 3 carry 6; and 22 at the front.' },
    { who: 'astro', say: '223729 tiles. Somebody order a lorry.', add: { t: '473 × 473', v: 223729 } },
  ] },
  'root-by-sight': { title: 'The paving square', scene: 'garden', cast: ['pixel', 'astro'], beats: [
    { who: null, say: 'Pip is laying 5776 square paving stones as one big square. How many go along each side?' },
    { who: 'pixel', say: 'It ends in 6, so the side ends in 4 or 6!' },
    { who: 'astro', say: 'Cover the last two digits: 57. 7 × 7 fits, 8 × 8 does not. So it is 74 or 76.', add: { t: '7 × 7', v: 49 } },
    { who: 'pixel', say: 'But which one?' },
    { who: 'astro', say: '7 × 8 is 56, and 57 is at least 56. So the side is above 75.', add: { t: '7 × 8', v: 56 } },
    { who: 'pixel', say: 'Checking it the long way: 76 × 76.', add: { t: '76 × 76', v: 5776 } },
    { who: 'astro', say: '76 stones a side.', add: { t: '70 + 6', v: 76 } },
  ] },
  'cube-root-sight': { title: 'The sugar-cube cube', scene: 'kitchen', cast: ['koi', 'scopey'], beats: [
    { who: null, say: 'For the school fair, Nova’s family stacks 54872 sugar cubes into one giant cube. How many cubes along each edge?' },
    { who: 'koi', say: 'It ends in 2. Only 8 cubed ends in 2, so the edge ends in 8.', add: { t: '8 × 8 × 8', v: 512 } },
    { who: 'scopey', say: 'Cover the last three digits: 54. 3 cubed is 27 and 4 cubed is 64.', add: { t: '3 × 3 × 3', v: 27 } },
    { who: 'koi', say: '54 sits between them, so the edge is in the thirties. Thirty-eight!' },
    { who: 'scopey', say: 'I am checking anyway: 38 × 38 × 38.', add: { t: '38 × 38 × 38', v: 54872 } },
    { who: 'koi', say: '38 cubes along each edge.', add: { t: '30 + 8', v: 38 } },
  ] },
  'osculator': { title: 'Shelves of nineteen', scene: 'library', cast: ['melody', 'scopey'], beats: [
    { who: null, say: 'The library has 4807 new books for shelves that hold 19 each. Will every shelf be exactly full?', add: { t: '4807 ÷ 19' } },
    { who: 'melody', say: 'For 19, one more than the 1 is 2. That is the osculator.' },
    { who: 'scopey', say: 'Chop off the 7, double it, and add it to 480.', add: { t: '480 + 7 × 2', v: 494 } },
    { who: 'melody', say: 'Again: chop off the 4, double it, add it to 49.', add: { t: '49 + 4 × 2', v: 57 } },
    { who: 'scopey', say: '57 is 3 × 19. So 4807 is in the 19 times table too.', add: { t: '3 × 19', v: 57 } },
    { who: 'melody', say: 'Every shelf full: 253 of them.', add: { t: '4807 ÷ 19', v: 253 } },
  ] },
  'root-long': { title: 'The solar field', scene: 'city', cast: ['samurai', 'goldlegend'], beats: [
    { who: null, say: 'A square field of solar panels holds 524176 panels. How many panels along one side?' },
    { who: 'samurai', say: 'Pairs from the right: 52, 41, 76. The biggest square in 52 is 49, so the side starts with 7, and 3 is left.', add: { t: '52 − 7 × 7', v: 3 } },
    { who: 'goldlegend', say: 'Divisor 14. Bring down 4: 34 ÷ 14 is 2, remainder 6.', add: { t: '34 − 14 × 2', v: 6 } },
    { who: 'samurai', say: 'Bring down 1: 61, less the duplex of 2. Then divide by 14 again: 4.', add: { t: '61 − 2 × 2', v: 57 } },
    { who: 'goldlegend', say: 'Remainder 1. Then 17 less 2 × 2 × 4 leaves 1, and 16 less 4 squared is nothing.', add: { t: '16 − 4 × 4', v: 0 } },
    { who: 'samurai', say: 'Exactly zero, so it is a perfect square: 724 a side.', add: { t: '700 + 20 + 4', v: 724 } },
  ] },
  'sutra-equations': { title: 'Mangoes and oranges', scene: 'market', cast: ['panda', 'samurai'], beats: [
    { who: null, say: 'At the stall, 2 mangoes and 3 oranges cost 13 coins, and 5 mangoes and 2 oranges cost 16. What does one orange cost?' },
    { who: 'panda', say: 'Two puzzles tangled together. Where do I start?' },
    { who: 'samurai', say: 'Crosswise, for the bottom: the oranges times the mangoes across, minus the other way.', add: { t: '3 × 5 − 2 × 2', v: 11 } },
    { who: 'panda', say: 'And for oranges the top swaps the oranges for the prices?' },
    { who: 'samurai', say: 'Not quite — for oranges, the prices across the mangoes: 13 × 5, less 16 × 2.', add: { t: '13 × 5 − 16 × 2', v: 33 } },
    { who: 'panda', say: 'Top over bottom: an orange is 3 coins.', add: { t: '33 ÷ 11', v: 3 } },
  ] },
  'quadratic-split': { title: 'The tile rectangle', scene: 'room', cast: ['astro', 'goldlegend'], beats: [
    { who: null, say: 'Mira’s tile pattern has area 6x² + 7x + 2. Vesper says it is a rectangle, (2x + ?) by (3x + ?). What goes in the first gap?' },
    { who: 'astro', say: 'The first and last numbers multiply to 12.', add: { t: '6 × 2', v: 12 } },
    { who: 'goldlegend', say: 'Split the 7 into 4 and 3. They multiply to 12 as well.', add: { t: '4 × 3', v: 12 } },
    { who: 'astro', say: '6 to 3 is 2 to 1, and 4 to 2 is 2 to 1. The same proportion!', add: { t: '6 ÷ 3', v: 2 } },
    { who: 'goldlegend', say: 'That ratio is a side: 2x + 1. First by first, 6x² ÷ 2x is 3x; last by last, 2 ÷ 1 is 2.' },
    { who: 'astro', say: '(2x + 1)(3x + 2). The first gap is 1.', add: { t: '2 ÷ 2', v: 1 } },
  ] },
  'pick-the-sutra': { title: 'Three sums, three tools', scene: 'hall', cast: ['comet', 'goldlegend'], beats: [
    { who: null, say: 'At the contest, Dax turns over three products: 98 × 97, 46 × 44 and 43 × 27.' },
    { who: 'comet', say: 'Crosswise for all of them, fast — oops, I carried the wrong digit.' },
    { who: 'goldlegend', say: 'Pick first. 98 and 97 are both near 100: gaps 2 and 3.', add: { t: '(98 − 3) × 100 + 2 × 3', v: 9506 } },
    { who: 'comet', say: '46 × 44: same front, and 6 + 4 makes ten. 4 × 5, then 6 × 4.', add: { t: '4 × 5 × 100 + 6 × 4', v: 2024 } },
    { who: 'goldlegend', say: '43 × 27 is neither. That one is crosswise.', add: { t: '4 × 2 × 100 + (4 × 7 + 3 × 2) × 10 + 3 × 7', v: 1161 } },
    { who: 'comet', say: 'Three different tools, three right answers.' },
  ] },
};
