/* The stories of library (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'place-value': { title: 'The shelf mark', scene: 'library', cast: ['beaker', 'pixel'], beats: [
    { who: null, say: 'Every book in the library has a number on its spine. Pip is looking for book 4,372.', add: { t: '4,372' } },
    { who: 'pixel', say: 'There is a 3 in it. So I want shelf three, right?' },
    { who: 'beaker', say: 'Take it apart first. 4 thousands, 3 hundreds, 7 tens and 2 ones.', add: { t: '4000 + 300 + 70 + 2', v: 4372 } },
    { who: 'beaker', say: 'That 3 sits in the hundreds place. It is not three — it is three hundreds.', add: { t: '3 × 100', v: 300 } },
    { who: 'pixel', say: 'So the rooms go by thousands, the rows by hundreds…' },
    { who: 'beaker', say: 'Take that 3 away and 4,072 is left. It was worth 300. The place tells you what a digit means.', add: { t: '4,372 − 4,072', v: 300 } },
  ] },
  'compare-big': { title: 'Two big libraries', scene: 'library', cast: ['scopey', 'comet'], beats: [
    { who: null, say: 'The notice board says one library holds 98,765 books and another 102,345.' },
    { who: 'comet', say: 'The first one wins easily — look, nines and eights!' },
    { who: 'scopey', say: 'Count the digits before you look at them. The first has five digits…' },
    { who: 'scopey', say: '…and the second has six. It has reached a hundred thousand; the first has not.', add: { t: '102,345 − 98,765', v: 3580 } },
    { who: 'comet', say: 'So 102,345 > 98,765. Bigger digits don’t help if you have fewer places.' },
    { who: 'scopey', say: 'And if the digit count ties, go left to right. The first different digit decides.' },
  ] },
  'round-nearest': { title: 'About how many?', scene: 'library', cast: ['koi', 'comet'], beats: [
    { who: null, say: 'The library has 4,372 books. The poster outside should give a round number, to the nearest hundred.', add: { t: '4,372' } },
    { who: 'comet', say: 'Just chop the end off. 4,300!' },
    { who: 'koi', say: 'Wait. It sits between 4,300 and 4,400. Which one is it closer to?' },
    { who: 'koi', say: 'Halfway between them is 4,350.', add: { t: '(4300 + 4400) ÷ 2', v: 4350 } },
    { who: 'comet', say: 'And 4,372 is past halfway…' },
    { who: 'koi', say: 'So it rounds up. The poster says about 4,400 books.', add: { t: '4300 + 100', v: 4400 } },
  ] },
  'column-add': { title: 'The book sale', scene: 'library', cast: ['beaker', 'pixel'], beats: [
    { who: null, say: 'On Saturday the book sale raised 368 rupees. On Sunday it raised 457.', add: { t: '368 + 457' } },
    { who: 'beaker', say: 'Line them up by place and start on the right. Ones: 8 and 7.', add: { t: '8 + 7', v: 15 } },
    { who: 'pixel', say: 'Fifteen won’t fit in one column!' },
    { who: 'beaker', say: 'Keep the 5, and carry the ten over to the tens. Tens: 6 and 5, and the 1 carried.', add: { t: '6 + 5 + 1', v: 12 } },
    { who: 'pixel', say: 'Keep the 2, carry again! Hundreds: 3 and 4 and the 1.', add: { t: '3 + 4 + 1', v: 8 } },
    { who: 'beaker', say: 'Read it off: 8, 2, 5.', add: { t: '368 + 457', v: 825 } },
  ] },
  'column-sub': { title: 'Books still out', scene: 'library', cast: ['panda', 'comet'], beats: [
    { who: null, say: 'The library lent 532 books this month. 178 have come back. How many are still out?', add: { t: '532 − 178' } },
    { who: 'comet', say: 'Ones: 2 take away 8. That’s impossible.' },
    { who: 'panda', say: 'Exchange a ten for ten ones. Now you have 12 ones.', add: { t: '12 − 8', v: 4 } },
    { who: 'panda', say: 'The tens gave one away, so 3 is now 2. 2 take 7 — exchange again.', add: { t: '12 − 7', v: 5 } },
    { who: 'comet', say: 'And the hundreds lent one too: 4 take 1.', add: { t: '4 − 1', v: 3 } },
    { who: 'panda', say: '354 books still out. Nothing was lost — only packed differently.', add: { t: '532 − 178', v: 354 } },
  ] },
  'negative-numbers': { title: 'The frosty morning', scene: 'garden', cast: ['koi', 'pixel'], beats: [
    { who: null, say: 'At dawn the garden thermometer reads −3 °C. By lunch it is 8 degrees warmer.' },
    { who: 'pixel', say: 'Three and eight is eleven. It’s 11 degrees!' },
    { who: 'koi', say: 'Look at the thermometer. The first 3 degrees only get you back up to zero.', add: { t: '−3 + 3', v: 0 } },
    { who: 'koi', say: 'That used 3 of the 8. How many are left?', add: { t: '8 − 3', v: 5 } },
    { who: 'pixel', say: 'Five more above zero… so it is 5 degrees.', add: { t: '−3 + 8', v: 5 } },
    { who: 'koi', say: 'Get to zero first, then carry on. Zero splits the jump in two.' },
  ] },
  'roman-numerals': { title: 'The old clock', scene: 'room', cast: ['astro', 'beaker'], beats: [
    { who: null, say: 'On a shelf in Mira’s room is an old clock. Rafi spots letters on its face instead of numbers.' },
    { who: 'beaker', say: 'The number after VIII is IX. Why isn’t it VIIII?' },
    { who: 'astro', say: 'A small letter before a bigger one means take it away. I before X is one less than ten.', add: { t: '10 − 1', v: 9 } },
    { who: 'beaker', say: 'And XII at the top is 10 and 1 and 1.', add: { t: '10 + 1 + 1', v: 12 } },
    { who: 'astro', say: 'Now try the label on the back: XLIV. Split it — XL, then IV.' },
    { who: 'beaker', say: 'XL is ten less than fifty, and IV is one less than five.', add: { t: '50 − 10 + 5 − 1', v: 44 } },
  ] },
  'long-multiply': { title: 'Tiling the reading room', scene: 'library', cast: ['astro', 'beaker'], beats: [
    { who: null, say: 'The reading-room floor is 46 tiles long and 37 tiles wide. How many tiles?', add: { t: '46 × 37' } },
    { who: 'astro', say: 'Cut the floor into four rectangles: 40 and 6 one way, 30 and 7 the other.' },
    { who: 'beaker', say: 'The big corner.', add: { t: '40 × 30', v: 1200 } },
    { who: 'astro', say: 'Two long strips.', add: { t: '40 × 7 + 6 × 30', v: 460 } },
    { who: 'beaker', say: 'And the little corner.', add: { t: '6 × 7', v: 42 } },
    { who: 'astro', say: 'Add all four pieces together: the whole floor.', add: { t: '1200 + 460 + 42', v: 1702 } },
  ] },
  'short-division': { title: 'Packing the boxes', scene: 'library', cast: ['panda', 'melody'], beats: [
    { who: null, say: '347 old books are going to a school, packed 5 to a box.', add: { t: '347 ÷ 5' } },
    { who: 'melody', say: '3 hundreds won’t make 5 whole groups of hundreds.' },
    { who: 'panda', say: 'Then think of them as 34 tens. 5 goes into 34 six times, with 4 tens over.', add: { t: '34 − 5 × 6', v: 4 } },
    { who: 'melody', say: 'Those 4 tens join the 7 ones: 47. That makes 9 fives, with some over.', add: { t: '47 − 5 × 9', v: 2 } },
    { who: 'panda', say: 'So 69 full boxes, and 2 books left over for the class shelf.', add: { t: '69 × 5 + 2', v: 347 } },
  ] },
  'order-of-operations': { title: 'The library quiz', scene: 'library', cast: ['samurai', 'pixel'], beats: [
    { who: null, say: 'The quiz card at the library desk says: 2 + 3 × 4.' },
    { who: 'pixel', say: 'Easy! 2 and 3 is 5, times 4 is 20.' },
    { who: 'samurai', say: 'Everyone has to agree on an order, or the same sum gives two answers. Multiply first.', add: { t: '3 × 4', v: 12 } },
    { who: 'samurai', say: 'Then add the 2.', add: { t: '2 + 12', v: 14 } },
    { who: 'pixel', say: 'But what if I really meant to add first?' },
    { who: 'samurai', say: 'Then write brackets and it goes first.', add: { t: '(2 + 3) × 4', v: 20 } },
    { who: 'pixel', say: 'Without brackets, the card’s answer is 14.', add: { t: '2 + 3 × 4', v: 14 } },
  ] },
};
