/* The stories of lighthouse (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'pythagoras-side': { title: 'The mast rope', scene: 'harbour', cast: ['astro', 'scopey'], beats: [
    { who: null, say: 'A boat’s mast stands 12 m tall. A rope runs from the top to a ring on the deck 5 m from the mast’s foot. Mira needs to cut a new rope.', add: { t: '12 × 12 + 5 × 5' } },
    { who: 'scopey', say: 'We could climb the mast with a tape measure…' },
    { who: 'astro', say: 'No need. Mast, deck and rope make a right angle. Square the two short sides.', add: { t: '12 × 12', v: 144 } },
    { who: 'scopey', say: 'And the deck side.', add: { t: '5 × 5', v: 25 } },
    { who: 'astro', say: 'Together they make the square on the rope.', add: { t: '144 + 25', v: 169 } },
    { who: 'scopey', say: 'Which number times itself is 169? I’ll check 13.', add: { t: '13 × 13', v: 169 } },
    { who: 'astro', say: 'Thirteen metres of rope. Measured without leaving the deck.', add: { t: '169 ÷ 13', v: 13 } },
  ] },
  'trig-sides': { title: 'Whose side is it?', scene: 'beach', cast: ['astro', 'samurai'], beats: [
    { who: null, say: 'On the beach, Mira draws a right-angled triangle in the sand with a stick: 3 m along, 4 m up, 5 m along the slope.', add: { t: '3 + 4 + 5', v: 12 } },
    { who: 'samurai', say: 'The 5 m side faces the square corner. That one is the hypotenuse, whatever we do.' },
    { who: 'astro', say: 'Now stand at the corner at the bottom left. Which short side touches your feet?' },
    { who: 'samurai', say: 'The 3 m side runs from me to the square corner. So it is adjacent. The 4 m side is across from me: opposite.' },
    { who: 'astro', say: 'Now walk to the top corner and look again.' },
    { who: 'samurai', say: 'Now the 4 m side touches me, so it is adjacent — and 3 m is opposite. The names swapped!' },
    { who: 'astro', say: 'Only the hypotenuse keeps its name. Find the angle first, then name the sides.', add: { t: '3 × 3 + 4 × 4', v: 25 } },
  ] },
  'tan-height': { title: 'Measuring the tower', scene: 'harbour', cast: ['scopey', 'goldlegend'], beats: [
    { who: null, say: 'Theo wants the height of the lighthouse. He paces 40 m from its foot along the harbour wall, and Vesper measures the angle up to the lamp: 35°.', add: { t: '40 × 0.7' } },
    { who: 'scopey', say: 'We know the distance along the bottom, but not the height.' },
    { who: 'goldlegend', say: 'Every right-angled triangle with a 35° angle has the same shape. Its height is about 0.7 of its length.' },
    { who: 'scopey', say: 'So for a length of 10 m, the height would be…', add: { t: '10 × 0.7', v: 7 } },
    { who: 'goldlegend', say: 'Ours is four times as long.', add: { t: '4 × 7', v: 28 } },
    { who: 'scopey', say: 'Height = 40 × tan 35°. About 28 metres.', add: { t: '40 × 0.7', v: 28 } },
    { who: 'goldlegend', say: 'And the lamp-room plaque says 28 m.' },
  ] },
  'sin-cos-side': { title: 'The painter’s ladder', scene: 'city', cast: ['melody', 'astro'], beats: [
    { who: null, say: 'A painter leans a 10 m ladder on a tall wall at 53° to the ground. Ines wants to know how high it reaches.', add: { t: '10 × 0.8' } },
    { who: 'melody', say: 'The ladder is the slope — the hypotenuse. The height is the side opposite the 53° angle.' },
    { who: 'astro', say: 'Opposite with hypotenuse is sin. Sin 53° is about 0.8.' },
    { who: 'melody', say: 'So the height is 0.8 of the ladder — like 80% of 10.', add: { t: '80% of 10', v: 8 } },
    { who: 'astro', say: 'And the foot is out by cos 53°, about 0.6 of it.', add: { t: '10 × 0.6', v: 6 } },
    { who: 'melody', say: 'Check with squares: 6 squared and 8 squared should make 10 squared.', add: { t: '6 × 6 + 8 × 8', v: 100 } },
    { who: 'astro', say: 'It reaches 8 metres up.', add: { t: '10 × 0.8', v: 8 } },
  ] },
  'special-angles': { title: 'The folded napkin', scene: 'night', cast: ['goldlegend', 'astro'], beats: [
    { who: null, say: 'After supper, Vesper folds a square napkin corner to corner. Each half is a right-angled triangle with two equal short sides.' },
    { who: 'astro', say: 'Two equal angles and a right angle. The other two must share what is left of 180°.', add: { t: '180 − 90', v: 90 } },
    { who: 'goldlegend', say: 'So each is 45°. Opposite ÷ adjacent is one side over an equal side.', add: { t: '1 ÷ 1', v: 1 } },
    { who: 'astro', say: 'tan 45° = 1, exactly. Now an equilateral triangle, side 2, cut down the middle.', add: { t: '2 ÷ 2', v: 1 } },
    { who: 'goldlegend', say: 'Short side 1, slope 2. From the top corner — 30° — the 1 is opposite.', add: { t: '1 ÷ 2', v: 0.5 } },
    { who: 'astro', say: 'So sin 30° is exactly one half. No calculator — just a folded napkin.', add: { t: '60 ÷ 2', v: 30 } },
  ] },
  'bearings': { title: 'The way home', scene: 'night', cast: ['samurai', 'scopey'], beats: [
    { who: null, say: 'Night on the water. Kwame steers the keeper’s boat out from the lighthouse on a bearing of 065° to check a buoy.', add: { t: '65 + 180' } },
    { who: 'scopey', say: 'Now we need to get home. Which bearing?' },
    { who: 'samurai', say: 'Straight back is the opposite way — half a turn round.', add: { t: '360 ÷ 2', v: 180 } },
    { who: 'scopey', say: '065 is less than 180, so we can add half a turn without going past north.', add: { t: '65 + 180', v: 245 } },
    { who: 'samurai', say: 'Two-four-five. Let me check it: going back out, take half a turn off again.', add: { t: '245 − 180', v: 65 } },
    { who: 'scopey', say: 'Bearing 245. The lamp should be dead ahead.', add: { t: '65 + 180', v: 245 } },
  ] },
  'scatter-correlation': { title: 'The keeper’s log', scene: 'beach', cast: ['scopey', 'melody'], beats: [
    { who: null, say: 'The keeper logs, for 12 summer days, the hours of sunshine and the number of people on the beach. Theo plots a dot for each day.' },
    { who: 'melody', say: 'The dots drift up to the right. The dullest day, 2 hours of sun, had 60 people; the sunniest, 9 hours, had 240.', add: { t: '240 − 60', v: 180 } },
    { who: 'scopey', say: 'That is a positive correlation. And they crowd close to a line, so it is strong.' },
    { who: 'melody', say: 'The keeper also logged ice creams sold and sunburns treated. Those rise together too.' },
    { who: 'scopey', say: 'But ice cream does not cause sunburn. The sunshine causes both.' },
    { who: 'melody', say: 'So a scatter graph shows things moving together — never, by itself, which one causes which.' },
  ] },
  'best-fit-estimate': { title: 'Reading the line', scene: 'harbour', cast: ['samurai', 'melody'], beats: [
    { who: null, say: 'Kwame has plotted the harbour log and drawn a line of best fit. It passes through (4, 6) and (12, 10). What does it say at x = 8?', add: { t: '12 − 4', v: 8 } },
    { who: 'samurai', say: 'From x = 4 to x = 12 the line climbs from 6 to 10.', add: { t: '10 − 6', v: 4 } },
    { who: 'melody', say: 'Four up for eight across — a half for every one across.', add: { t: '4 ÷ 8', v: 0.5 } },
    { who: 'samurai', say: 'From x = 4 to x = 8 is 4 across, so it climbs 4 halves.', add: { t: '4 × 0.5', v: 2 } },
    { who: 'melody', say: 'So at x = 8 the line says 8.', add: { t: '6 + 4 × 0.5', v: 8 } },
    { who: 'samurai', say: 'Inside the data, so it is a fair guess. Out at x = 30, where nobody measured, I would not trust it.' },
  ] },
  'tree-diagram': { title: 'Two ferries', scene: 'harbour', cast: ['melody', 'goldlegend'], beats: [
    { who: null, say: 'The morning ferry is late on 1 day in 4. The evening ferry is late on 2 days in 5, whatever the morning one did. How often are both late?' },
    { who: 'melody', say: 'Think of 100 days. The morning ferry is late on a quarter of them.', add: { t: '100 ÷ 4', v: 25 } },
    { who: 'goldlegend', say: 'On two fifths of those 25 days, the evening one is late too.', add: { t: '25 ÷ 5 × 2', v: 10 } },
    { who: 'melody', say: 'So both are late on 10 days in 100. That is one tenth.', add: { t: '10 ÷ 100', v: 0.1 } },
    { who: 'goldlegend', say: 'Multiply along the branches. A fraction of a fraction.' },
    { who: 'melody', say: 'One quarter times two fifths: two twentieths, which is one tenth.', add: { t: '1 ÷ 4 × 2 ÷ 5', v: 0.1 } },
  ] },
  'expected-frequency': { title: 'Sixty nights of weather', scene: 'night', cast: ['melody', 'scopey'], beats: [
    { who: null, say: 'The keeper’s logbook shows rain on about 3 nights in every 10. Theo is planning the next 60 nights and wants to know how many will be wet.', add: { t: '60 ÷ 10 × 3' } },
    { who: 'scopey', say: 'Sixty nights. How many rainy ones should I plan for?' },
    { who: 'melody', say: 'Three in every ten. So split the 60 nights into tens first.', add: { t: '60 ÷ 10', v: 6 } },
    { who: 'scopey', say: 'Six lots of ten nights, with 3 wet ones in each.', add: { t: '6 × 3', v: 18 } },
    { who: 'melody', say: 'Or straight away: the chance times the number of nights. 0.3 of 60.', add: { t: '60 × 0.3', v: 18 } },
    { who: 'scopey', say: 'So it will rain on exactly 18 nights?' },
    { who: 'melody', say: 'Probably not exactly — maybe 15, maybe 21. Expect about 18: that is the middle the real count wobbles round, not a promise.' },
  ] },
  'inequalities': { title: 'The weight limit', scene: 'harbour', cast: ['samurai', 'scopey'], beats: [
    { who: null, say: 'The lighthouse crane can lift less than 19 tonnes. The cradle weighs 4 tonnes and each crate weighs 3 tonnes. How many crates can go up at once?', add: { t: '3 × 5 + 4' } },
    { who: 'samurai', say: 'Call the crates x. Then 3x + 4 < 19. Take the cradle off both sides.', add: { t: '19 − 4', v: 15 } },
    { who: 'samurai', say: 'Now 3x < 15. Share both sides by 3: x < 5.', add: { t: '15 ÷ 3', v: 5 } },
    { who: 'scopey', say: 'So five crates? Let me check.', add: { t: '3 × 5 + 4', v: 19 } },
    { who: 'samurai', say: 'Exactly 19 — and the limit is less than 19. Five is one too many.' },
    { who: 'scopey', say: 'Four crates, then.', add: { t: '3 × 4 + 4', v: 16 } },
    { who: 'samurai', say: 'The biggest whole number below 5.', add: { t: '5 − 1', v: 4 } },
  ] },
};
