/* The stories of logic (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  parity: { title: 'The hopscotch frog', scene: 'garden', cast: ['pixel', 'koi'], beats: [
    { who: null, say: 'Pip has chalked a number line on the garden path. A toy frog starts on 0 and must make 7 hops, each one step left or right.', add: { t: '7 hops' } },
    { who: 'pixel', say: 'I bet I can get it back to 0. Left, right, left, right… oh. I am on 1. Let me try again.' },
    { who: 'koi', say: 'Watch the numbers it lands on. Even, odd, even, odd — every hop flips it, like a switch.' },
    { who: 'pixel', say: 'So after 6 hops it is on an even number…', add: { t: '6 ÷ 2', v: 3 } },
    { who: 'koi', say: 'And the 7th hop flips it to odd. Always. 0 is even, so it can never land there after 7 hops.' },
    { who: 'pixel', say: 'So I could have stopped trying before I started! After 8 hops, though…', add: { t: '7 + 1', v: 8 } },
  ] },
  'worst-case': { title: 'Socks in a power cut', scene: 'room', cast: ['comet', 'scopey'], beats: [
    { who: null, say: 'The lights are out. Dax needs a matching pair from a drawer of 5 red, 7 blue and 4 green socks, and the bus leaves in two minutes.', add: { t: '5 + 7 + 4', v: 16 } },
    { who: 'comet', say: 'Sixteen socks! Do I have to take them all out to be safe?' },
    { who: 'scopey', say: 'Think of the unluckiest grab. What is the most socks you could take and still have no pair?' },
    { who: 'comet', say: 'One red, one blue, one green. Three, and nothing matches.', add: { t: '1 + 1 + 1', v: 3 } },
    { who: 'scopey', say: 'And the next sock has to be one of those colours. So it matches, whatever happens.' },
    { who: 'comet', say: 'Four socks and I am sure. I will make the bus!', add: { t: '3 + 1', v: 4 } },
  ] },
  pigeonhole: { title: 'Birthday days', scene: 'hall', cast: ['koi', 'beaker'], beats: [
    { who: null, say: 'The hall is filling for assembly. Nova wonders how many children must be in it before two of them MUST share the weekday they were born on.' },
    { who: 'beaker', say: 'There are 7 days. Think of them as 7 boxes, and each child goes in the box of their day.', add: { t: '7 boxes' } },
    { who: 'koi', say: 'Seven children could all be on different days. So seven is not enough to be sure.' },
    { who: 'beaker', say: 'But the eighth child has to go in a box that already has someone in it.', add: { t: '7 + 1', v: 8 } },
    { who: 'koi', say: 'And for three on the same day? Two in every box first is 14, still no three…', add: { t: '7 × 2', v: 14 } },
    { who: 'beaker', say: 'So the fifteenth child makes three. We do not know which day — only that it must happen.', add: { t: '7 × 2 + 1', v: 15 } },
  ] },
  'calendar-days': { title: 'A hundred days to the fair', scene: 'fair', cast: ['panda', 'pixel'], beats: [
    { who: null, say: 'It is Tuesday. The poster says the summer fair is exactly 100 days away. Pip wants to know which day of the week it falls on.', add: { t: '100 days' } },
    { who: 'pixel', say: 'I will count it on the calendar. Wednesday, Thursday, Friday…' },
    { who: 'panda', say: 'Every 7 days it is Tuesday again. So throw away as many whole weeks as you can.', add: { t: '7 × 14', v: 98 } },
    { who: 'pixel', say: 'Fourteen weeks is 98 days, and that is Tuesday again. That leaves…', add: { t: '100 − 98', v: 2 } },
    { who: 'panda', say: 'Two days on from Tuesday.' },
    { who: 'pixel', say: 'Wednesday, Thursday! The fair is on a Thursday, and I did not need the calendar at all.', add: { t: '100 − 7 × 14', v: 2 } },
  ] },
  'missing-digit-divisibility': { title: 'The smudged ticket', scene: 'train', cast: ['beaker', 'melody'], beats: [
    { who: null, say: 'Ines has a train ticket number with one digit smudged: 3▢72. The guard says every ticket number divides exactly by 9.', add: { t: '3 + 7 + 2', v: 12 } },
    { who: 'melody', say: 'Could the smudge be anything from 0 to 9? That is ten numbers to divide.' },
    { who: 'beaker', say: 'A number divides by 9 when its digits add to a multiple of 9. The digits you can see make 12.' },
    { who: 'melody', say: 'The next multiple of 9 is 18. So the smudge is…', add: { t: '18 − 12', v: 6 } },
    { who: 'beaker', say: 'And 27 would need a digit of 15, which is no digit. So 6 is the only one. Check it.', add: { t: '3672 ÷ 9', v: 408 } },
    { who: 'melody', say: 'Ticket 3672. One sum instead of ten!', add: { t: '18 − 12', v: 6 } },
  ] },
  'list-systematically': { title: 'Locker codes', scene: 'stadium', cast: ['scopey', 'comet'], beats: [
    { who: null, say: 'The stadium lockers use 3-digit codes whose digits add up to 5. Dax wants to know how many codes there are.', add: { t: 'digits add to 5' } },
    { who: 'comet', say: 'Easy: 500, 410, 302, 113, 221… um, did I say 410 already?' },
    { who: 'scopey', say: 'Make a list in order. Start with first digit 1: the last two add to 4. That gives 104, 113, 122, 131, 140.', add: { t: '4 + 1', v: 5 } },
    { who: 'comet', say: 'First digit 2: the last two add to 3, so 203, 212, 221, 230. Four.', add: { t: '3 + 1', v: 4 } },
    { who: 'scopey', say: 'Each row is one shorter. Then 3, then 2, then just 500.' },
    { who: 'comet', say: 'Fifteen codes, and I know none are missing or doubled.', add: { t: '5 + 4 + 3 + 2 + 1', v: 15 } },
  ] },
  'truth-tellers': { title: 'Two at the gate', scene: 'palace', cast: ['goldlegend', 'koi'], beats: [
    { who: null, say: 'At the palace gate stand Asha and Bilal. One rule: a knight always tells the truth, a liar always lies. Asha says, "Bilal is a liar."' },
    { who: null, say: 'Bilal says, "Asha and I are the same kind." Nova and Vesper must decide who to ask for directions.' },
    { who: 'koi', say: 'There are only so many ways to fill in knight or liar for two people.', add: { t: '2 × 2', v: 4 } },
    { who: 'goldlegend', say: 'Suppose Asha lies. Then Bilal is a knight, so he is the same kind as her. A knight and a liar cannot be the same. No.' },
    { who: 'koi', say: 'So Asha is a knight. Bilal is a liar — and he really is a different kind from her, so his words are false. It fits.' },
    { who: 'goldlegend', say: 'Exactly one way works. Ask Asha.', add: { t: '4 − 3', v: 1 } },
  ] },
  'digit-puzzles': { title: 'The rubbed-out sum', scene: 'library', cast: ['beaker', 'pixel'], beats: [
    { who: null, say: 'On the library whiteboard someone has rubbed out two digits of a sum: 4A + B7 = 82.', add: { t: '4A + B7 = 82' } },
    { who: 'pixel', say: 'Two missing digits — a hundred possibilities! Where do I even start?' },
    { who: 'beaker', say: 'At the ones. A + 7 has to end in 2, and only 5 does that: 5 + 7 = 12.', add: { t: '5 + 7', v: 12 } },
    { who: 'pixel', say: 'So A is 5, and the 1 from 12 carries into the tens.' },
    { who: 'beaker', say: 'Tens: 4 + B + 1 must make 8.', add: { t: '8 − 4 − 1', v: 3 } },
    { who: 'pixel', say: 'B is 3! Check: 45 + 37.', add: { t: '45 + 37', v: 82 } },
  ] },
  'remainder-puzzles': { title: 'Eggs in the kitchen', scene: 'kitchen', cast: ['samurai', 'melody'], beats: [
    { who: null, say: 'Kwame packs eggs in 3s, then 4s, then 5s. Every time, 2 eggs are left over. There are more than 2 eggs. What is the fewest there could be?' },
    { who: 'melody', say: 'Should we try 3, then 4, then 5… one at a time?' },
    { who: 'samurai', say: 'Take the 2 spare eggs away. The rest packs exactly into 3s, 4s and 5s.' },
    { who: 'melody', say: 'So the rest is a number that 3, 4 and 5 all go into. The smallest is…', add: { t: '3 × 4 × 5', v: 60 } },
    { who: 'samurai', say: 'Now put the 2 spare eggs back.', add: { t: '60 + 2', v: 62 } },
    { who: 'melody', say: 'Check: 62 ÷ 4 is 15 with 2 over. Sixty-two eggs.', add: { t: '15 × 4 + 2', v: 62 } },
  ] },
  invariants: { title: 'The board that keeps a secret', scene: 'bus', cast: ['panda', 'comet'], beats: [
    { who: null, say: 'On a long bus ride Suki writes 1 to 10 on a pad. Dax rubs out two numbers and writes their difference, again and again, until one is left.', add: { t: '1 + 2 + 3 + 4 + 5 + 6 + 7 + 8 + 9 + 10', v: 55 } },
    { who: 'panda', say: 'Before you finish, I can tell you if the last number is odd or even.' },
    { who: 'comet', say: 'You cannot! I choose which numbers to rub out.' },
    { who: 'panda', say: 'Swap 9 and 4 for 5. The total drops by 8 — twice the 4. Every move drops it by an even amount.', add: { t: '9 + 4 − 5', v: 8 } },
    { who: 'comet', say: 'So the total stays odd, because 55 is odd… and at the end the total IS the last number.' },
    { who: 'panda', say: 'Odd, whatever you choose. Something that never changes is called an invariant.', add: { t: '55 − 2 × 27', v: 1 } },
  ] },
};
