/* The stories of mine (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'compare-integers': { title: 'The coldest night', scene: 'night', cast: ['pixel', 'koi'], beats: [
    { who: null, say: 'A winter night. Pip’s thermometer reads −7 °C. Nova’s, across the street, reads −3 °C.' },
    { who: 'pixel', say: 'Seven is bigger than three, so −7 is the bigger number. Mine wins!' },
    { who: 'koi', say: 'Which one is colder, though? Yours is seven below zero. Mine is only three below.', add: { t: '0 − 7', v: -7 } },
    { who: 'pixel', say: 'Mine’s colder… so on the thermometer, −7 is lower down.' },
    { who: 'koi', say: 'Lower down means smaller. From −7 you have to climb 4 degrees just to reach −3.', add: { t: '−7 + 4', v: -3 } },
    { who: 'pixel', say: 'So −3 is the bigger number, and −7 is less than −3. The one higher up wins.' },
  ] },
  'lift-moves': { title: 'The car park lift', scene: 'city', cast: ['comet', 'panda'], beats: [
    { who: null, say: 'The car park under the city tower has four floors below ground. Dax and Suki get in the lift at level −4.' },
    { who: null, say: 'They want the café, 9 floors up from where they are.', add: { t: '−4 + 9' } },
    { who: 'comet', say: 'Four and nine is thirteen — press 13!' },
    { who: 'panda', say: 'Wait. The first 4 floors only take us up to ground level, 0.', add: { t: '−4 + 4', v: 0 } },
    { who: 'panda', say: 'That uses 4 of the 9. How many are left to go above ground?', add: { t: '9 − 4', v: 5 } },
    { who: 'comet', say: 'Five! The café is on level 5, not 13.', add: { t: '−4 + 9', v: 5 } },
    { who: 'panda', say: 'Go to zero first, then carry on with what is left.' },
  ] },
  'integer-gap': { title: 'The diver and the gull', scene: 'harbour', cast: ['beaker', 'koi'], beats: [
    { who: null, say: 'At the harbour a diver is 6 metres under the water, at −6 m. A gull sits on a post 5 metres above it.' },
    { who: 'koi', say: 'How far apart are they? Six take away five is one.' },
    { who: 'beaker', say: 'But they are on opposite sides of the water. Take it apart at the surface, 0.' },
    { who: 'beaker', say: 'From the diver up to the surface.', add: { t: '0 − (−6)', v: 6 } },
    { who: 'koi', say: 'And from the surface up to the gull is 5 more.', add: { t: '5 − 0', v: 5 } },
    { who: 'beaker', say: 'Zero is between them, so add the two parts.', add: { t: '6 + 5', v: 11 } },
    { who: 'koi', say: 'Eleven metres apart. The higher one minus the lower one.', add: { t: '5 − (−6)', v: 11 } },
  ] },
  'add-negative': { title: 'The club account', scene: 'shop', cast: ['melody', 'pixel'], beats: [
    { who: null, say: 'Pip runs the model-club account at the corner shop. It has 5 coins in it. A bill for 8 coins arrives.', add: { t: '5 + (−8)' } },
    { who: 'pixel', say: 'We’re adding the bill, so the account gets bigger… no, that can’t be right.' },
    { who: 'melody', say: 'A bill is a negative number. Adding it takes money away — 8 of it.' },
    { who: 'melody', say: 'The first 5 coins bring the account down to zero.', add: { t: '5 − 5', v: 0 } },
    { who: 'pixel', say: 'And there are still 3 coins of the bill left to pay.', add: { t: '8 − 5', v: 3 } },
    { who: 'melody', say: 'So the balance is −3. It just means 3 still owed. Nobody’s in trouble.', add: { t: '5 + (−8)', v: -3 } },
  ] },
  'subtract-negative': { title: 'The pattern on the board', scene: 'hall', cast: ['samurai', 'comet'], beats: [
    { who: null, say: 'Before the hall assembly, Kwame writes a column of sums on the whiteboard. Dax is sure the last one is wrong.' },
    { who: 'samurai', say: 'Read down the list. Each time I take away one less.', add: { t: '5 − 2', v: 3 } },
    { who: 'comet', say: 'Then 5 − 1 is 4, and 5 − 0 is 5. The answer goes up by one each line.', add: { t: '5 − 0', v: 5 } },
    { who: 'samurai', say: 'So what must come next, when I take away −1?', add: { t: '5 − (−1)', v: 6 } },
    { who: 'comet', say: 'Six! Taking away a negative is adding. So 5 − (−3) is 5 + 3.', add: { t: '5 + 3', v: 8 } },
    { who: 'samurai', say: 'The pattern does not stop at zero. Neither does the answer.', add: { t: '5 − (−3)', v: 8 } },
  ] },
  'ups-and-downs': { title: 'The fair game', scene: 'fair', cast: ['scopey', 'beaker'], beats: [
    { who: null, say: 'At the fair, Rafi’s game scores go: −5, then +8, −9, +3 and −6.', add: { t: '−5 + 8 − 9 + 3 − 6' } },
    { who: 'beaker', say: 'Minus five, plus eight is three, minus nine is… I keep losing track.' },
    { who: 'scopey', say: 'Sort them first. The order doesn’t change the total. All the ups together.', add: { t: '8 + 3', v: 11 } },
    { who: 'beaker', say: 'And all the downs together.', add: { t: '5 + 9 + 6', v: 20 } },
    { who: 'scopey', say: 'Up 11, down 20. The downs win by 9.', add: { t: '11 − 20', v: -9 } },
    { who: 'beaker', say: 'My score is −9. Two additions and one take-away.', add: { t: '−5 + 8 − 9 + 3 − 6', v: -9 } },
  ] },
  'multiply-signs': { title: 'The table that kept going', scene: 'room', cast: ['astro', 'samurai'], beats: [
    { who: null, say: 'Mira and Kwame are doing homework in Mira’s room. The question is −4 × (−8).', add: { t: '−4 × (−8)' } },
    { who: 'astro', say: 'Two minuses make a plus — but my teacher says I have to explain why.' },
    { who: 'samurai', say: 'Write the −8 times table, and let the multiplier go down one at a time.', add: { t: '1 × (−8)', v: -8 } },
    { who: 'astro', say: 'Then 0 × (−8) is 0. Each line down, the answer goes up by 8.', add: { t: '0 × (−8)', v: 0 } },
    { who: 'samurai', say: 'Keep the pattern going below zero.', add: { t: '−1 × (−8)', v: 8 } },
    { who: 'astro', say: 'Up by 8 each time, so four steps below zero gives 32.', add: { t: '8 × 4', v: 32 } },
    { who: 'samurai', say: 'The pattern had no other choice. Negative times negative is positive.', add: { t: '−4 × (−8)', v: 32 } },
  ] },
  'divide-signs': { title: 'The new freezer', scene: 'kitchen', cast: ['goldlegend', 'melody'], beats: [
    { who: null, say: 'Vesper’s family has a new freezer. In 4 hours its temperature falls by 24 degrees.', add: { t: '−24 ÷ 4' } },
    { who: 'melody', say: 'The change is −24, shared over 4 hours. What is the change each hour?' },
    { who: 'goldlegend', say: 'Sizes first.', add: { t: '24 ÷ 4', v: 6 } },
    { who: 'melody', say: 'A negative shared out stays negative. It is falling every hour, not rising.' },
    { who: 'goldlegend', say: 'Check it backwards. Four hours of −6.', add: { t: '4 × (−6)', v: -24 } },
    { who: 'melody', say: 'Minus six degrees an hour. Same rule as multiplying.', add: { t: '−24 ÷ 4', v: -6 } },
  ] },
  'negative-squares': { title: 'The calculator argument', scene: 'library', cast: ['scopey', 'comet'], beats: [
    { who: null, say: 'In the library, Dax types −3² into a calculator and it says −9. He is sure it is broken.' },
    { who: 'comet', say: 'Minus three times minus three is plus nine. Everyone knows that!', add: { t: '(−3) × (−3)', v: 9 } },
    { who: 'scopey', say: 'That is what (−3)² means — with brackets. You didn’t type brackets.' },
    { who: 'scopey', say: 'Without them, the power goes first. Square the 3.', add: { t: '3 × 3', v: 9 } },
    { who: 'comet', say: 'And then the minus in front makes it negative.', add: { t: '0 − 3 × 3', v: -9 } },
    { who: 'scopey', say: 'So the calculator is right. −3² is −9, and (−3)² is 9. The brackets decide.', add: { t: '−(3 × 3)', v: -9 } },
  ] },
};
