/* The stories of palace (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'square-dots': { title: 'The parade ground', scene: 'palace', cast: ['astro', 'pixel'], beats: [
    { who: null, say: 'Morning at the Square Palace. The guards line up on the parade ground: 7 rows, 7 guards in every row.', add: { t: '7 × 7' } },
    { who: 'pixel', say: 'I will count them! One, two, three… wait, did I count that one already?' },
    { who: 'astro', say: 'Look at the shape, Pip. As wide as it is tall. That is a square, so it is 7 times 7.' },
    { who: 'pixel', say: 'Then when the band joins, 8 rows of 8 is a bigger square!', add: { t: '8 × 8', v: 64 } },
    { who: 'astro', say: 'Exactly. We write 7 × 7 as 7² — seven squared. The little 2 means two sevens multiplied.' },
    { who: 'pixel', say: 'So this morning there are forty-nine guards. Forty-nine is a square number!', add: { t: '7 × 7', v: 49 } },
  ] },
  'odd-staircase': { title: 'The garden tiles', scene: 'garden', cast: ['astro', 'koi'], beats: [
    { who: null, say: 'In the palace garden, Nova lays tiles: 1 gold tile, then 3 around its corner, then 5, then 7, then 9.', add: { t: '1 + 3 + 5 + 7 + 9' } },
    { who: 'koi', say: 'Every new layer wraps round the corner like an L. And every time, it is a square again!' },
    { who: 'astro', say: 'Because an L round an n-square is n, plus n, plus one corner. Always odd.', add: { t: '4 + 4 + 1', v: 9 } },
    { who: 'koi', say: 'I laid five layers, so my square is 5 tiles wide.' },
    { who: 'astro', say: 'Five odd numbers make five squared. No adding needed.', add: { t: '5 × 5', v: 25 } },
    { who: 'koi', say: 'Twenty-five tiles. The odd numbers were climbing a staircase of squares.', add: { t: '1 + 3 + 5 + 7 + 9', v: 25 } },
  ] },
  'teen-squares': { title: 'The carpet in the hall', scene: 'palace', cast: ['astro', 'beaker'], beats: [
    { who: null, say: 'The palace needs a square carpet for the throne room, 13 tiles along each side. How many tiles?', add: { t: '13 × 13' } },
    { who: 'beaker', say: 'I like taking numbers apart. 13 is 10 and 3.' },
    { who: 'astro', say: 'Then the carpet is a 10-by-10 square in the middle…', add: { t: '10 × 10', v: 100 } },
    { who: 'beaker', say: '…two long strips, 10 by 3, down two sides…', add: { t: '2 × 10 × 3', v: 60 } },
    { who: 'astro', say: 'And a tiny 3-by-3 corner where the strips meet.', add: { t: '3 × 3', v: 9 } },
    { who: 'beaker', say: 'One hundred and sixty-nine. Every teen square is 100, plus two strips, plus a corner.', add: { t: '100 + 60 + 9', v: 169 } },
  ] },
  'square-endings': { title: 'The locked door', scene: 'palace', cast: ['scopey', 'comet'], beats: [
    { who: null, say: 'A puzzle door in the palace: "The code is the last digit of 47 × 47." Dax reaches for a pencil.', add: { t: '47 × 47' } },
    { who: 'comet', say: 'Forty-seven times forty-seven… that is going to take ages!' },
    { who: 'scopey', say: 'Only the ones digits make the ones digit. The 40s never reach that column. So just do 7 × 7.', add: { t: '7 × 7', v: 49 } },
    { who: 'comet', say: 'Ends in 9! And no square EVER ends in 2, 3, 7 or 8?' },
    { who: 'scopey', say: 'Never. I checked all ten digits. The code is 9 — and the full answer ends in it too.', add: { t: '47 × 47', v: 2209 } },
    { who: 'comet', say: 'Nine. The door clicks open. One digit was all we needed.', add: { t: '2209 − 2200', v: 9 } },
  ] },
  'root-of-square': { title: 'The square courtyard', scene: 'palace', cast: ['astro', 'panda'], beats: [
    { who: null, say: 'A square courtyard is paved with 196 stones. Suki wants to know how many stones long each side is.', add: { t: '196' } },
    { who: 'panda', say: 'Which number times itself makes 196? I would have to guess.' },
    { who: 'astro', say: 'Not guess — trap it. 10 × 10 is 100 and 20 × 20 is 400. So it is in the teens.', add: { t: '20 × 20', v: 400 } },
    { who: 'panda', say: 'It ends in 6. Four times four ends in 6… and so does six times six.' },
    { who: 'astro', say: 'Then try 14 and 16. 14 × 14 is just right.', add: { t: '14 × 14', v: 196 } },
    { who: 'panda', say: 'Fourteen stones a side. The square root undoes the square.', add: { t: '196 ÷ 14', v: 14 } },
  ] },
  'powers-index': { title: 'The doubling rice', scene: 'room', cast: ['goldlegend', 'pixel'], beats: [
    { who: null, say: 'Pip finds an old board game in the palace attic. Put 1 grain on the first square, then double it on each square after.', add: { t: '1' } },
    { who: 'pixel', say: '1, 2, 4, 8, 16… that is tiny. It will never be much.' },
    { who: 'goldlegend', say: 'Five doublings.', add: { t: '2 × 2 × 2 × 2 × 2', v: 32 } },
    { who: 'pixel', say: 'Thirty-two. So ten doublings is only sixty-four?' },
    { who: 'goldlegend', say: 'No. Two lots of five doublings, one after the other.', add: { t: '32 × 32', v: 1024 } },
    { who: 'pixel', say: 'Over a thousand! The little number, the power, says how many twos. 2 to the power 5 is thirty-two.', add: { t: '2 × 2 × 2 × 2 × 2', v: 32 } },
  ] },
  'cube-and-root': { title: 'The sugar-cube tower', scene: 'kitchen', cast: ['astro', 'comet'], beats: [
    { who: null, say: 'In the palace kitchen, Dax builds a giant cube from sugar cubes: 4 long, 4 wide and 4 high.', add: { t: '4 × 4 × 4' } },
    { who: 'comet', say: 'One layer is a 4-by-4 square.', add: { t: '4 × 4', v: 16 } },
    { who: 'astro', say: 'And there are four layers. That is 4 cubed — four, three times over.', add: { t: '16 × 4', v: 64 } },
    { who: 'comet', say: 'What if the cook says her cube used 42,875 cubes? What is its side?' },
    { who: 'astro', say: 'Drop the last three digits: 42. Three cubed is 27, four cubed is 64 — so the tens digit is 3. It ends in 5, so the root ends in 5.', add: { t: '35 × 35 × 35', v: 42875 } },
    { who: 'comet', say: 'Thirty-five! But mine is smaller: sixty-four cubes, four on a side.', add: { t: '4 × 4 × 4', v: 64 } },
  ] },
  'square-minus': { title: 'The banner that shrank', scene: 'palace', cast: ['samurai', 'melody'], beats: [
    { who: null, say: 'A square palace banner must be 19 squares on each side. Ines has a 20-by-20 cloth.', add: { t: '19 × 19' } },
    { who: 'melody', say: 'Twenty by twenty is easy: four hundred squares.', add: { t: '20 × 20', v: 400 } },
    { who: 'samurai', say: 'Cut a strip one wide off the side, and one off the bottom. Twenty squares each.', add: { t: '2 × 20', v: 40 } },
    { who: 'melody', say: 'Wait — the corner square was in both strips. I cut it off twice.' },
    { who: 'samurai', say: 'So put one back. Four hundred, take forty, add one.', add: { t: '400 − 40 + 1', v: 361 } },
    { who: 'melody', say: 'Three hundred and sixty-one squares on the banner.', add: { t: '19 × 19', v: 361 } },
  ] },
  'square-near-50': { title: 'The rooftop garden', scene: 'city', cast: ['samurai', 'scopey'], beats: [
    { who: null, say: 'A square rooftop garden is 47 metres on each side. Theo needs its area for the seed order.', add: { t: '47 × 47' } },
    { who: 'scopey', say: 'I would do long multiplication, then check it twice.' },
    { who: 'samurai', say: 'Try 50 instead. 50 × 50 is 2500 — and 47 is 3 below it.', add: { t: '50 × 50', v: 2500 } },
    { who: 'samurai', say: 'Two strips, each 50 by 3, come off. That is 300.', add: { t: '2 × 50 × 3', v: 300 } },
    { who: 'scopey', say: 'And the 3-by-3 corner was taken twice, so 9 goes back.', add: { t: '2500 − 300 + 9', v: 2209 } },
    { who: 'samurai', say: 'Two thousand two hundred and nine square metres. Near fifty, every square is quick.', add: { t: '47 × 47', v: 2209 } },
  ] },
  'either-side': { title: 'Seats in the stadium', scene: 'stadium', cast: ['samurai', 'koi'], beats: [
    { who: null, say: 'A stadium block has 23 rows of 17 seats. Nova is selling tickets and needs the total.', add: { t: '23 × 17' } },
    { who: 'koi', say: 'I know my tables — but not the 23 times table.' },
    { who: 'samurai', say: 'Look at the middle. 23 and 17 are both 3 away from 20.', add: { t: '(23 + 17) ÷ 2', v: 20 } },
    { who: 'koi', say: 'So it is nearly a 20-by-20 square…', add: { t: '20 × 20', v: 400 } },
    { who: 'samurai', say: 'With a 3-by-3 corner missing. Take it away.', add: { t: '400 − 9', v: 391 } },
    { who: 'koi', say: 'Three hundred and ninety-one seats. Middle squared, take the gap squared.', add: { t: '23 × 17', v: 391 } },
  ] },
  'index-laws': { title: 'Stars over the palace', scene: 'night', cast: ['goldlegend', 'beaker'], beats: [
    { who: null, say: 'A clear night on the palace roof. Rafi reads that there are about 3 × 10⁴ stars in one patch of sky, and 2 × 10³ patches like it.', add: { t: '30,000 × 2,000' } },
    { who: 'beaker', say: 'Thirty thousand times two thousand… that is a lot of zeros to keep track of.' },
    { who: 'goldlegend', say: 'Multiply the front numbers.', add: { t: '3 × 2', v: 6 } },
    { who: 'beaker', say: 'And ten to the four times ten to the three is seven tens multiplied — add the powers.', add: { t: '4 + 3', v: 7 } },
    { who: 'goldlegend', say: 'Six times ten to the seven.', add: { t: '6 × 10,000,000', v: 60000000 } },
    { who: 'beaker', say: 'Sixty million stars — and I never wrote a single long row of zeros.', add: { t: '30,000 × 2,000', v: 60000000 } },
  ] },
};
