/* The stories of quarry (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'number-families': { title: 'Hoops by the pond', scene: 'pond', cast: ['pixel', 'koi'], beats: [
    { who: null, say: 'On a frosty morning the thermometer by the pond reads −4 °C. Pip and Nova chalk three hoops, one inside another, on the path.', add: { t: '−4' } },
    { who: 'pixel', say: 'The little hoop is for counting numbers — 1, 2, 3. The ducks: 7. So 7 goes in the middle.' },
    { who: 'koi', say: 'The next hoop adds zero. How many ice skates do we own? None. Zero is still an amount.' },
    { who: 'pixel', say: 'But −4 isn’t something you can count. Where does it go?' },
    { who: 'koi', say: 'The biggest hoop, the integers. It holds numbers below zero: 4 degrees colder than zero.', add: { t: '0 − 4', v: -4 } },
    { who: 'pixel', say: 'So 7 is in all three hoops, 0 in two, and −4 only in the big one!' },
  ] },
  'odd-even-rules': { title: 'Partners for the dance', scene: 'hall', cast: ['beaker', 'comet'], beats: [
    { who: null, say: '37 children from one school and 58 from another meet in the hall for a partner dance. Will everyone have a partner?', add: { t: '37 + 58' } },
    { who: 'comet', say: 'I’ll add them first and then check… hang on, give me a minute.' },
    { who: 'beaker', say: 'No need. 58 stand in pairs with nobody over.', add: { t: '58 ÷ 2', v: 29 } },
    { who: 'beaker', say: '37 is 18 pairs and one child on their own.', add: { t: '18 × 2 + 1', v: 37 } },
    { who: 'comet', say: 'Put them together and the pairs stay pairs. Just that one child is left. Odd plus even is odd!', add: { t: '37 + 58', v: 95 } },
    { who: 'beaker', say: 'And if both groups were odd, the two lonely ones would dance with each other.' },
  ] },
  'number-types': { title: 'The pebble shapes', scene: 'garden', cast: ['astro', 'pixel'], beats: [
    { who: null, say: 'Mira has 28 smooth pebbles from the garden path. Can they make a square, a triangle or a cube?', add: { t: '28' } },
    { who: 'pixel', say: 'A square! 5 rows of 5 is 25… and 6 rows of 6 is 36. 28 falls between.', add: { t: '5 × 5', v: 25 } },
    { who: 'astro', say: 'A cube needs 3 × 3 × 3. That’s 27 — one pebble short of 28.', add: { t: '3 × 3 × 3', v: 27 } },
    { who: 'pixel', say: 'A triangle, then? A row of 1, a row of 2, a row of 3…' },
    { who: 'astro', say: 'Keep going, each row one longer, up to 7.', add: { t: '1 + 2 + 3 + 4 + 5 + 6 + 7', v: 28 } },
    { who: 'pixel', say: 'Every pebble used. 28 is triangular!' },
  ] },
  'prime-stones': { title: 'Towers of stones', scene: 'city', cast: ['beaker', 'koi'], beats: [
    { who: null, say: 'Rafi and Nova build number towers. The rule: only prime stones — 2, 3, 5, 7 and so on.' },
    { who: 'koi', say: 'My tower is 2, 2, 3 and 5. Multiply them to see what it builds.', add: { t: '2 × 2', v: 4 } },
    { who: 'beaker', say: 'Then 4 times 3 is 12, and 12 times 5 is 60.', add: { t: '4 × 3 × 5', v: 60 } },
    { who: 'koi', say: 'Can you build 60 with different prime stones?' },
    { who: 'beaker', say: '60 is 6 × 10… but 6 breaks into 2 × 3 and 10 into 2 × 5. The same four stones!', add: { t: '2 × 3 × 2 × 5', v: 60 } },
    { who: 'koi', say: 'Every number has exactly one set of prime stones. Only the order can change.' },
  ] },
  'sieve-root': { title: 'The library puzzle', scene: 'library', cast: ['scopey', 'panda'], beats: [
    { who: null, say: 'In the library, Theo finds a puzzle card: is 187 a prime number?', add: { t: '187' } },
    { who: 'scopey', say: 'I’ll try dividing by every number up to 186. Just to be sure.' },
    { who: 'panda', say: 'Only primes, and only up to 13. Look: 13 × 13 is 169.', add: { t: '13 × 13', v: 169 } },
    { who: 'panda', say: '14 × 14 is 196, past 187. So if it splits, one factor is 13 or smaller.', add: { t: '14 × 14', v: 196 } },
    { who: 'scopey', say: 'Then 2, 3, 5, 7, 11, 13 at most. 2 no, 3 no, 5 no, 7 no… 11!', add: { t: '11 × 17', v: 187 } },
    { who: 'panda', say: 'Not prime. And the biggest prime we could ever have needed was 13.', add: { t: '169 ÷ 13', v: 13 } },
  ] },
  'coprime': { title: 'The painted cogs', scene: 'fair', cast: ['melody', 'astro'], beats: [
    { who: null, say: 'At the fair, a machine has two cogs: one with 35 teeth, one with 48. A tooth on each is painted red, and the red teeth touch.', add: { t: '35 and 48' } },
    { who: 'melody', say: 'When do the red teeth meet again? Does it depend on what the numbers share?' },
    { who: 'astro', say: 'Let’s see their stones. 35 is 5 × 7.', add: { t: '5 × 7', v: 35 } },
    { who: 'astro', say: 'And 48 is 2 × 2 × 2 × 2 × 3. Does 5 go into 48? No. Does 7? No.', add: { t: '2 × 2 × 2 × 2 × 3', v: 48 } },
    { who: 'melody', say: 'Not one stone shared — they’re coprime. Only 1 divides both.' },
    { who: 'astro', say: 'So the red teeth only meet again after 35 × 48 teeth go by. Every tooth meets every tooth first.', add: { t: '35 × 48', v: 1680 } },
  ] },
  'factor-count-stones': { title: 'Bags of biscuits', scene: 'bakery', cast: ['panda', 'beaker'], beats: [
    { who: null, say: 'The bakery has 72 biscuits to pack into equal bags, none left over. How many different bag sizes could work?', add: { t: '2 × 2 × 2 × 3 × 3', v: 72 } },
    { who: 'beaker', say: 'I’ll list them: 1, 2, 3, 4, 6, 8… and hope I don’t miss any.' },
    { who: 'panda', say: 'Use the stones. 72 is three 2s and two 3s. A bag size takes some of the 2s and some of the 3s.' },
    { who: 'panda', say: 'Of the 2s it can take none, one, two or three: four choices.', add: { t: '3 + 1', v: 4 } },
    { who: 'beaker', say: 'Of the 3s: none, one or two. Three choices.', add: { t: '2 + 1', v: 3 } },
    { who: 'panda', say: 'Each pair of choices builds a different size. Twelve bag sizes.', add: { t: '4 × 3', v: 12 } },
  ] },
  'ending-decimals': { title: 'The calculator screen', scene: 'shop', cast: ['melody', 'scopey'], beats: [
    { who: null, say: 'At the shop, Theo divides on a calculator. 7 ÷ 40 stops neatly, but 1 ÷ 3 fills the screen with 3s.', add: { t: '7 ÷ 40', v: 0.175 } },
    { who: 'scopey', say: 'Why do some stop and some go on for ever? I checked it three times.' },
    { who: 'melody', say: 'Look at the stones on the bottom. 40 is 2 × 2 × 2 × 5 — only 2s and 5s.', add: { t: '2 × 2 × 2 × 5', v: 40 } },
    { who: 'melody', say: 'And 1,000 is made of 2s and 5s too, so 40 fits into it exactly.', add: { t: '1,000 ÷ 40', v: 25 } },
    { who: 'scopey', say: 'But 3 isn’t a 2 or a 5. No ten, hundred or thousand ever splits into threes.' },
    { who: 'melody', say: 'That’s why 1/3 never ends. And 7/40 is 175 thousandths.', add: { t: '25 × 7 ÷ 1,000', v: 0.175 } },
  ] },
  'rational-roots': { title: 'The lonely stone', scene: 'night', cast: ['samurai', 'goldlegend'], beats: [
    { who: null, say: 'Under the stars, Kwame asks Vesper: 7 × 7 is 49. Can √50 be written as one whole number over another?', add: { t: '7 × 7', v: 49 } },
    { who: 'samurai', say: 'Try 99/14. 99 × 99 is 9,801…', add: { t: '99 × 99', v: 9801 } },
    { who: 'samurai', say: '…and 50 × 14 × 14 is 9,800. So close!', add: { t: '50 × 14 × 14', v: 9800 } },
    { who: 'goldlegend', say: 'Look at the stones of 50.', add: { t: '2 × 5 × 5', v: 50 } },
    { who: 'goldlegend', say: 'A square has every stone in pairs. The 5s pair up. The 2 is alone.' },
    { who: 'samurai', say: 'And a fraction squared has its stones in pairs, top and bottom. It can never make a lonely 2.' },
    { who: 'goldlegend', say: 'So √50 is irrational. A real length — but no fraction is exactly it.' },
  ] },
};
