/* The stories of setisland (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'set-member': { title: 'The seven-step bridge', scene: 'beach', cast: ['scopey', 'pixel'], beats: [
    { who: null, say: 'On the beach at Set Island, a sign by the rock pools says: only numbers in M = {multiples of 7} may cross. Pip is holding 91.', add: { t: '91' } },
    { who: 'pixel', say: 'Is 91 allowed? I would have to list 7, 14, 21… all the way up. That takes for ever!' },
    { who: 'scopey', say: 'You do not need the list. The set has a rule. Just test your number against it.' },
    { who: 'pixel', say: 'Does 7 go into 91 with nothing left?', add: { t: '91 ÷ 7', v: 13 } },
    { who: 'scopey', say: 'Thirteen exactly. Check it back the other way.', add: { t: '13 × 7', v: 91 } },
    { who: 'pixel', say: 'So 91 is a member of M. I can cross! A rule answers it in one sum.', add: { t: '91 ÷ 7', v: 13 } },
  ] },
  'set-count': { title: 'Shells in a row', scene: 'beach', cast: ['beaker', 'koi'], beats: [
    { who: null, say: 'Rafi and Nova number 100 shells along the sand. Every 6th shell is a spotted one. How many spotted shells?', add: { t: '100 ÷ 6' } },
    { who: 'koi', say: 'Six, twelve, eighteen… I could count them all.' },
    { who: 'beaker', say: 'Find the last one instead. 6 × 16 is 96, and 6 × 17 is 102 — too far.', add: { t: '6 × 16', v: 96 } },
    { who: 'koi', say: 'So the spotted ones are 6 × 1 up to 6 × 16. They are numbered 1 to 16!' },
    { who: 'beaker', say: 'And how many spotted shells between 41 and 47? None — that is the empty set.', add: { t: '47 − 41', v: 6 } },
    { who: 'koi', say: 'Sixteen spotted shells, counted without counting.', add: { t: '96 ÷ 6', v: 16 } },
  ] },
  'union-meet': { title: 'Two teams, one bus', scene: 'bus', cast: ['panda', 'comet'], beats: [
    { who: null, say: 'Team A is shirts 2, 4, 6, 8 and 10. Team B is shirts 3, 6 and 9. Everybody in either team gets on the bus.', add: { t: '5 + 3' } },
    { who: 'comet', say: 'Five plus three — eight seats! Done!', add: { t: '5 + 3', v: 8 } },
    { who: 'panda', say: 'Look again, Dax. Shirt 6 is in both teams. Does one child need two seats?' },
    { who: 'comet', say: 'Oh. The overlap — A intersect B — has one child in it. I counted them twice.', add: { t: '1', v: 1 } },
    { who: 'panda', say: 'So take the double count away once.', add: { t: '5 + 3 − 1', v: 7 } },
    { who: 'comet', say: 'Seven seats for A union B. The shared ones go in once.', add: { t: '5 + 3 − 1', v: 7 } },
  ] },
  'venn-count': { title: 'The club list', scene: 'hall', cast: ['scopey', 'melody'], beats: [
    { who: null, say: 'In the island hall, 14 children sign up for cricket and 11 for chess. 5 signed up for both.', add: { t: '14 + 11' } },
    { who: 'melody', say: 'So 25 children came to sign up.', add: { t: '14 + 11', v: 25 } },
    { who: 'scopey', say: 'Check that. The 5 in both are on the cricket list AND the chess list. You counted them twice.' },
    { who: 'melody', say: 'Draw the circles: cricket only is 9, chess only is 6, and 5 in the middle.', add: { t: '14 − 5', v: 9 } },
    { who: 'scopey', say: 'Add the three parts.', add: { t: '9 + 5 + 6', v: 20 } },
    { who: 'melody', say: 'Twenty children. Add both circles, take the overlap once.', add: { t: '14 + 11 − 5', v: 20 } },
  ] },
  substitute: { title: 'The matchstick pattern', scene: 'room', cast: ['samurai', 'pixel'], beats: [
    { who: null, say: 'Pip builds a row of triangles out of matchsticks. Kwame writes on the board: matches = 3n + 2, for n triangles.', add: { t: '3 × 4 + 2' } },
    { who: 'pixel', say: 'What is n? It is a letter, not a number!' },
    { who: 'samurai', say: 'n is a box. Right now you have 4 triangles, so put 4 in the box.' },
    { who: 'pixel', say: '3n means 3 times n. So 3 times 4…', add: { t: '3 × 4', v: 12 } },
    { who: 'samurai', say: 'Then the plus 2.', add: { t: '12 + 2', v: 14 } },
    { who: 'pixel', say: 'Fourteen matches! And the same rule tells me 40 triangles would need 122.', add: { t: '3 × 4 + 2', v: 14 } },
  ] },
  'subset-count': { title: 'Toppings on the pizza', scene: 'kitchen', cast: ['goldlegend', 'comet'], beats: [
    { who: null, say: 'The island café has 4 toppings: olives, peppers, corn and mushroom. Dax wants to try every different pizza.', add: { t: '2 × 2 × 2 × 2' } },
    { who: 'comet', say: 'One topping, two toppings, three… I keep losing count!' },
    { who: 'goldlegend', say: 'Each topping: on or off. Two choices.', add: { t: '2', v: 2 } },
    { who: 'comet', say: 'Olives on or off, then peppers on or off… so it doubles for every topping!', add: { t: '2 × 2', v: 4 } },
    { who: 'goldlegend', say: 'Four toppings.', add: { t: '2 × 2 × 2 × 2', v: 16 } },
    { who: 'comet', say: 'Sixteen pizzas — and one of them is plain, with no topping at all. The empty set counts too!', add: { t: '2 × 2 × 2 × 2', v: 16 } },
  ] },
  'like-terms': { title: 'The fruit basket', scene: 'market', cast: ['melody', 'koi'], beats: [
    { who: null, say: 'Ines writes the market order in algebra: x for a crate of apples, y for bananas. 3x + 2y + 4x + y.', add: { t: '3 + 4' } },
    { who: 'koi', say: 'Three plus two plus four plus one — ten crates! So 10xy?' },
    { who: 'melody', say: 'Ten crates, yes, but not ten of one thing. Keep apples with apples.', add: { t: '3 + 4', v: 7 } },
    { who: 'koi', say: 'And bananas with bananas. The lone y means one crate.', add: { t: '2 + 1', v: 3 } },
    { who: 'melody', say: 'So it is 7x + 3y. Shorter, and still true for any crate size.' },
    { who: 'koi', say: 'Seven crates of apples and three of bananas. Like with like.', add: { t: '3 + 4', v: 7 } },
  ] },
  'solve-balance': { title: 'The weighing scale', scene: 'shop', cast: ['samurai', 'panda'], beats: [
    { who: null, say: 'On the shop scale: 3 bags of marbles and 4 loose marbles balance 19 loose marbles. Every bag holds the same.', add: { t: '19' } },
    { who: 'panda', say: 'So 3x + 4 = 19. How many marbles in a bag?' },
    { who: 'samurai', say: 'Take 4 loose marbles off both sides. Still level.', add: { t: '19 − 4', v: 15 } },
    { who: 'panda', say: 'Three bags balance fifteen. So share both sides into three.', add: { t: '15 ÷ 3', v: 5 } },
    { who: 'samurai', say: 'Check it on the scale.', add: { t: '3 × 5 + 4', v: 19 } },
    { who: 'panda', say: 'Five marbles in each bag. Same to both sides, always.', add: { t: '(19 − 4) ÷ 3', v: 5 } },
  ] },
  'nth-term': { title: 'Beach huts', scene: 'beach', cast: ['beaker', 'scopey'], beats: [
    { who: null, say: 'Beach hut 1 is 5 metres from the café, hut 2 is 8, hut 3 is 11, hut 4 is 14. How far is hut 20?', add: { t: '5 + 19 × 3' } },
    { who: 'scopey', say: 'Each hut is 3 metres further on. Twenty huts, so 20 steps of 3?' },
    { who: 'beaker', say: 'Careful — hut 1 is already there. From hut 1 to hut 20 is only 19 steps.', add: { t: '20 − 1', v: 19 } },
    { who: 'scopey', say: 'Nineteen steps of three.', add: { t: '19 × 3', v: 57 } },
    { who: 'beaker', say: 'Add the 5 metres to hut 1.', add: { t: '57 + 5', v: 62 } },
    { who: 'scopey', say: 'Sixty-two. And 3 × 20 + 2 agrees: the rule is 3n + 2.', add: { t: '3 × 20 + 2', v: 62 } },
  ] },
  'line-graph': { title: 'The tide post', scene: 'harbour', cast: ['astro', 'comet'], beats: [
    { who: null, say: 'At the harbour, a tide post starts 1 metre deep and the water rises 2 metres every hour: y = 2x + 1.', add: { t: '2 × 3 + 1' } },
    { who: 'comet', say: 'After 3 hours it has gone up… 3 metres? No wait!' },
    { who: 'astro', say: 'Two metres every hour. Three hours of that.', add: { t: '2 × 3', v: 6 } },
    { who: 'comet', say: 'And it started at 1 metre, where the line crosses the side.', add: { t: '6 + 1', v: 7 } },
    { who: 'astro', say: 'Plot the hours and the depths and the points line up straight — the same climb every hour.' },
    { who: 'comet', say: 'Seven metres deep after three hours.', add: { t: '2 × 3 + 1', v: 7 } },
  ] },
};
