/* The stories of shapecity (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'sides-and-corners': { title: 'The shape walk', scene: 'city', cast: ['astro', 'pixel'], beats: [
    { who: null, say: 'Mira and Pip walk home through the city, spotting shapes. A paving stone by the fountain has six sides.' },
    { who: 'pixel', say: 'It looks like a honeycomb cell. Is it a pentagon?' },
    { who: 'astro', say: 'Count before you name it. Put your finger on one side and go round.', add: { t: '1 + 1 + 1 + 1 + 1 + 1', v: 6 } },
    { who: 'pixel', say: 'Six sides. And the corners… six as well!' },
    { who: 'astro', say: 'Always. Every side ends at a corner and the next side starts there. Six sides is a hexagon; a pentagon has five.' },
    { who: 'pixel', say: 'So the stop sign over there, with one more side than two squares, is…', add: { t: '4 + 4', v: 8 } },
    { who: 'astro', say: 'Eight sides — an octagon. Octa means eight, like an octopus.', add: { t: '6 + 2', v: 8 } },
  ] },
  'lines-of-symmetry': { title: 'Folding the kite paper', scene: 'room', cast: ['koi', 'beaker'], beats: [
    { who: null, say: 'Nova and Rafi are cutting paper for a window display. Nova holds up a square and a long rectangle.' },
    { who: 'beaker', say: 'The square folds four ways: two straight across and two corner to corner.', add: { t: '2 + 2', v: 4 } },
    { who: 'koi', say: 'Then the rectangle must fold four ways too.' },
    { who: 'beaker', say: 'Try corner to corner.' },
    { who: 'koi', say: 'Oh — the long edge lands on the short edge. The corners stick out. That is not a fold line.' },
    { who: 'beaker', say: 'So only the two straight folds work: top to bottom, and side to side.', add: { t: '4 − 2', v: 2 } },
    { who: 'koi', say: 'Two lines of symmetry. Cutting it in equal halves is not enough — the halves must land on each other.', add: { t: '1 + 1', v: 2 } },
  ] },
  'kinds-of-triangle': { title: 'The garden frame', scene: 'garden', cast: ['scopey', 'panda'], beats: [
    { who: null, say: 'Theo and Suki are building a bean frame from three canes: 5, 5 and 8 hands long.', add: { t: '5 + 5 + 8', v: 18 } },
    { who: 'scopey', say: 'What kind of triangle will it be? I want to label the plan properly.' },
    { who: 'panda', say: 'Look for sides that match. The two 5s do.' },
    { who: 'scopey', say: 'Two equal sides — isosceles. And the angles at the bottom of those sides match too.' },
    { who: 'panda', say: 'If all three canes were 5, it would be equilateral. If none matched, scalene.', add: { t: '5 × 3', v: 15 } },
    { who: 'scopey', say: 'Two equal canes, one long one. Isosceles it is.', add: { t: '8 − 5', v: 3 } },
  ] },
  'four-sided-shapes': { title: 'The tile shop', scene: 'shop', cast: ['astro', 'melody'], beats: [
    { who: null, say: 'In a tile shop, Ines picks up a tile with four equal sides. It is leaning over like a pushed square.' },
    { who: 'melody', say: 'Four equal sides — so it is a square.' },
    { who: 'astro', say: 'Check the corners. Are they right angles?' },
    { who: 'melody', say: 'No — two are pointy and two are wide. Their sizes still add to a full turn.', add: { t: '60 + 120 + 60 + 120', v: 360 } },
    { who: 'astro', say: 'Four equal sides but no right angles makes a rhombus. A square is a rhombus that also has square corners.' },
    { who: 'melody', say: 'And two pairs of parallel sides, like every parallelogram.', add: { t: '1 + 1', v: 2 } },
  ] },
  'faces-edges-vertices': { title: 'The paper lanterns', scene: 'festival', cast: ['beaker', 'comet'], beats: [
    { who: null, say: 'Rafi and Dax are building a hexagonal prism lantern out of straws for the festival.' },
    { who: 'comet', say: 'How many straws do we need? Let me count the edges on the picture… I lost count.' },
    { who: 'beaker', say: 'Count by the ends. Round the front hexagon: 6 straws.', add: { t: '6', v: 6 } },
    { who: 'comet', say: 'Round the back one, another 6. Then 6 joining the ends.', add: { t: '6 + 6 + 6', v: 18 } },
    { who: 'beaker', say: 'Check with Euler: 8 faces and 12 corners, take away 2.', add: { t: '8 + 12 − 2', v: 18 } },
    { who: 'comet', say: 'Eighteen straws. The rule agrees — so we did not miss one.', add: { t: '3 × 6', v: 18 } },
  ] },
  'kinds-of-angle': { title: 'The opening door', scene: 'hall', cast: ['pixel', 'panda'], beats: [
    { who: null, say: 'The hall door swings open. Pip and Suki watch the angle between the door and the wall.' },
    { who: 'pixel', say: 'Just a little open — a sharp angle. That is acute!' },
    { who: 'panda', say: 'Now it is square to the wall, like the corner of a book. A right angle.', add: { t: '360 ÷ 4', v: 90 } },
    { who: 'pixel', say: 'Wider than that, but not flat against the wall yet — obtuse.' },
    { who: 'panda', say: 'Flat is a straight line, two right angles.', add: { t: '90 + 90', v: 180 } },
    { who: 'pixel', say: 'And if a door could swing past flat, that would be a reflex angle — more than 180° but less than a full turn.', add: { t: '180 + 90', v: 270 } },
  ] },
  'coordinates-and-moves': { title: 'The treasure grid', scene: 'beach', cast: ['comet', 'koi'], beats: [
    { who: null, say: 'On the beach, Nova draws a grid in the sand. The shell is buried at (3, 2).' },
    { who: 'comet', say: 'Three up, two across!' },
    { who: 'koi', say: 'Across first, then up — along the corridor, then up the stairs. Three across, two up.' },
    { who: null, say: 'The tide pushes the shell 4 squares right and 1 square up.' },
    { who: 'comet', say: 'Right only changes the across number.', add: { t: '3 + 4', v: 7 } },
    { who: 'koi', say: 'And up changes only the up number.', add: { t: '2 + 1', v: 3 } },
    { who: 'comet', say: 'Dig at (7, 3)! The across number is 7.', add: { t: '3 + 4', v: 7 } },
  ] },
  'angles-on-a-line': { title: 'The see-saw', scene: 'stadium', cast: ['scopey', 'melody'], beats: [
    { who: null, say: 'A ramp leans on a flat path by the stadium. On one side it makes an angle of 125° with the path.', add: { t: '125' } },
    { who: 'melody', say: 'What is the angle on the other side? I have no protractor.' },
    { who: 'scopey', say: 'You do not need one. The path is a straight line, and a straight line is half a turn.', add: { t: '360 ÷ 2', v: 180 } },
    { who: 'melody', say: 'So the two angles share the 180° between them.' },
    { who: 'scopey', say: 'Take away the one you know.', add: { t: '180 − 125', v: 55 } },
    { who: 'melody', say: 'Fifty-five degrees. And all the way round a point would be 360°.', add: { t: '125 + 55', v: 180 } },
    { who: 'scopey', say: 'So the missing angle is 55°.', add: { t: '180 − 125', v: 55 } },
  ] },
  'angles-in-a-shape': { title: 'Torn corners', scene: 'room', cast: ['samurai', 'astro'], beats: [
    { who: null, say: 'Kwame cuts out a paper triangle. Two of its angles are 50° and 60°.', add: { t: '50 + 60', v: 110 } },
    { who: 'astro', say: 'Tear off all three corners and put the points together.' },
    { who: 'samurai', say: 'They make a straight line. Every time, whatever triangle I cut.', add: { t: '90 + 90', v: 180 } },
    { who: 'astro', say: 'So the three angles fill 180°. Take away the two you know.', add: { t: '180 − 110', v: 70 } },
    { who: 'samurai', say: 'And a four-sided shape cuts into two triangles, corner to corner.' },
    { who: 'astro', say: 'So its angles make two lots of 180°.', add: { t: '2 × 180', v: 360 } },
    { who: 'samurai', say: 'The third angle of my triangle is 70°.', add: { t: '180 − 50 − 60', v: 70 } },
  ] },
  'round-the-circle': { title: 'The rolling wheel', scene: 'city', cast: ['goldlegend', 'comet'], beats: [
    { who: null, say: 'Dax and Vesper wheel a bike through the city. Its wheel is 60 cm across.', add: { t: '60' } },
    { who: 'comet', say: 'How far does it roll in one turn? About 60 cm?' },
    { who: 'goldlegend', say: 'More. The distance round is about 3.14 times the distance across.' },
    { who: 'comet', say: 'Three times first.', add: { t: '3 × 60', v: 180 } },
    { who: 'goldlegend', say: 'Then the small part.', add: { t: '0.14 × 60', v: 8.4 } },
    { who: 'comet', say: '188.4 cm every turn — nearly two metres!', add: { t: '180 + 8.4', v: 188.4 } },
  ] },
  'construct-triangle': { title: 'Three straws', scene: 'room', cast: ['astro', 'pixel'], beats: [
    { who: null, say: 'Pip has three straws, 3 cm, 4 cm and 7 cm long, and wants a triangle. Mira gets out a ruler and compasses.', add: { t: '3 + 4' } },
    { who: 'pixel', say: 'Easy — just join the ends up!' },
    { who: 'astro', say: 'Draw the 7 cm one as the base first. Then swing a 3 cm arc from one end and a 4 cm arc from the other.' },
    { who: 'pixel', say: 'The arcs only just touch — right on the base line. There is no corner sticking up.' },
    { who: 'astro', say: 'Because the two short sides add up to exactly the base. Laid end to end, they lie flat along it.', add: { t: '3 + 4', v: 7 } },
    { who: 'pixel', say: 'So if the long one were a bit shorter, the arcs would cross above the base?', add: { t: '7 − 1', v: 6 } },
    { who: 'astro', say: 'Yes. The two shorter sides must add up to MORE than the longest. 3 + 4 is not more than 7, so no triangle.', add: { t: '3 + 4', v: 7 } },
  ] },
  'perpendicular-bisector': { title: 'The bird bath', scene: 'garden', cast: ['koi', 'scopey'], beats: [
    { who: null, say: 'On Nova’s garden plan, two lemon trees stand at (2, 1) and (10, 1). She wants a bird bath exactly as far from one tree as from the other.', add: { t: '10 − 2', v: 8 } },
    { who: 'koi', say: 'Halfway between them works: 4 from each.', add: { t: '8 ÷ 2', v: 4 } },
    { who: 'scopey', say: 'That is one spot. Now open the compasses wider and swing equal arcs from both trees.' },
    { who: 'koi', say: 'They cross above the line and below it. Both crossings are one compass-width from each tree.' },
    { who: 'scopey', say: 'Join them: a straight line through the middle, square to the trees. Check (6, 4) — 4 across and 3 up from either tree.', add: { t: '4 × 4 + 3 × 3', v: 25 } },
    { who: 'koi', say: 'The same 25 from both trees. So every spot on that line would do.' },
    { who: 'scopey', say: 'The line through the middle is x = 6.', add: { t: '(2 + 10) ÷ 2', v: 6 } },
  ] },
  'angle-bisector': { title: 'The corner path', scene: 'city', cast: ['panda', 'beaker'], beats: [
    { who: null, say: 'Two walls of a city park meet at a corner of 84°. Suki wants a path from the corner that splits it into two equal angles.', add: { t: '84 ÷ 2' } },
    { who: 'beaker', say: 'Half of 84 — so each side of the path makes 42°.', add: { t: '84 ÷ 2', v: 42 } },
    { who: 'panda', say: 'And to mark it out with no protractor: one arc from the corner that cuts both walls.' },
    { who: 'beaker', say: 'Then equal arcs from those two marks, crossing. The path runs from the corner through the crossing.' },
    { who: 'panda', say: 'Two triangles with the same three sides, one each side of the path. Same triangle, so the same angle.' },
    { who: 'beaker', say: 'Check it: two halves make the whole corner.', add: { t: '42 × 2', v: 84 } },
    { who: 'panda', say: 'Each half is 42°. The path is the angle bisector.', add: { t: '84 − 42', v: 42 } },
  ] },
};
