/* The stories of strategy (docs/CHAPTER-CONTRACT.md): loaded with story-data.js, never on first paint. */
export const STORIES = {
  'work-backwards': { title: 'The sticker swap', scene: 'room', cast: ['pixel', 'scopey'], beats: [
    { who: null, say: 'Pip had some stickers. He gave 6 to his sister, got 10 more at a swap, then gave half of what he had to Theo. Now he has 14.' },
    { who: 'pixel', say: 'And now I cannot remember how many I started with. Was it loads?' },
    { who: 'scopey', say: 'Start at the end. Giving half away left you 14, so before that you had double.', add: { t: '14 × 2', v: 28 } },
    { who: 'pixel', say: 'Before that, the swap gave me 10. So take them off.', add: { t: '28 − 10', v: 18 } },
    { who: 'scopey', say: 'And before THAT you gave your sister 6. Put them back.', add: { t: '18 + 6', v: 24 } },
    { who: 'scopey', say: 'Now check forwards: 24, take 6, add 10, halve. Do we land on 14?', add: { t: '(24 − 6 + 10) ÷ 2', v: 14 } },
    { who: 'pixel', say: 'We do! I started with 24 — I just undid it backwards, last thing first.', add: { t: '14 × 2 − 10 + 6', v: 24 } },
  ] },
  'guess-check-improve': { title: 'Two page numbers', scene: 'library', cast: ['comet', 'koi'], beats: [
    { who: null, say: 'Dax opens a library book in the middle. Nova covers the page numbers and says: "They multiply to make 506. What do they add up to?"', add: { t: '506' } },
    { who: 'comet', say: 'Easy. 20 and 21!', add: { t: '20 × 21', v: 420 } },
    { who: 'koi', say: 'Check it — 420. Too small, so go up. That guess still told us something.' },
    { who: 'comet', say: 'Then 25 and 26.', add: { t: '25 × 26', v: 650 } },
    { who: 'koi', say: 'Too big. So it is between 20 and 25. And 506 ends in 6 — try 22 and 23.', add: { t: '22 × 23', v: 506 } },
    { who: 'comet', say: 'Bang on. Three guesses, and each one pointed the way.', add: { t: '22 + 23', v: 45 } },
  ] },
  'make-a-table': { title: 'The savings race', scene: 'market', cast: ['beaker', 'melody'], beats: [
    { who: null, say: 'Rafi has 30 coins and saves 4 a week. Ines has 6 coins but saves 10 a week. When will they have the same?' },
    { who: 'beaker', say: 'Let me make a table. Week 1: I have 34…', add: { t: '30 + 4', v: 34 } },
    { who: 'melody', say: '…and I have 16. You are still way ahead.', add: { t: '6 + 10', v: 16 } },
    { who: 'beaker', say: 'Look at the gap, though. It started at 24…', add: { t: '30 − 6', v: 24 } },
    { who: 'melody', say: 'And every week I catch up the difference in what we save.', add: { t: '10 − 4', v: 6 } },
    { who: 'beaker', say: 'So the rows will close the gap in 24 ÷ 6 weeks. No need to write all of them.', add: { t: '24 ÷ 6', v: 4 } },
  ] },
  'find-the-rule': { title: 'The matchstick fence', scene: 'kitchen', cast: ['astro', 'pixel'], beats: [
    { who: null, say: 'Pip is building rows of squares from matchsticks: 4 sticks for one square, 7 for two, 10 for three. He wants to know how many for 25 squares.' },
    { who: 'pixel', say: 'I will just build all 25 and count!' },
    { who: 'astro', say: 'You will run out of matches first. Each new square only needs 3 more sticks.', add: { t: '7 − 4', v: 3 } },
    { who: 'astro', say: 'Step back to shape 0 — no squares, just the first stick on the left.', add: { t: '4 − 3', v: 1 } },
    { who: 'pixel', say: 'So 25 squares is 25 lots of 3…', add: { t: '25 × 3', v: 75 } },
    { who: 'astro', say: '…plus that one stick at the start. Seventy-six.', add: { t: '75 + 1', v: 76 } },
  ] },
  'bar-model': { title: 'Shells on the beach', scene: 'beach', cast: ['panda', 'pixel'], beats: [
    { who: null, say: 'Suki and Pip collected 52 shells between them. Pip collected 14 more than Suki.' },
    { who: 'pixel', say: 'So I have about 30? I am bad at guessing.' },
    { who: 'panda', say: 'Draw it. My bar, then your bar the same length with an extra 14 stuck on. Cut the extra off.', add: { t: '52 − 14', v: 38 } },
    { who: 'panda', say: 'Now the two bars are the same, so share it equally.', add: { t: '38 ÷ 2', v: 19 } },
    { who: 'pixel', say: 'That is your bar. Mine is your bar plus the extra.', add: { t: '19 + 14', v: 33 } },
    { who: 'panda', say: 'Check the other way: take my 19 from the 52 and see what is left for you. The bars did the thinking.', add: { t: '52 − 19', v: 33 } },
  ] },
  'heads-and-legs': { title: 'The farm count', scene: 'garden', cast: ['samurai', 'beaker'], beats: [
    { who: null, say: 'At a city farm, Rafi counts 12 heads and 34 legs in the hen-and-goat pen.' },
    { who: 'beaker', say: 'I cannot see which is which from here. How many goats?' },
    { who: 'samurai', say: 'Pretend they are all hens. That is only so many legs.', add: { t: '12 × 2', v: 24 } },
    { who: 'beaker', say: 'But there are 34, so some legs are not explained.', add: { t: '34 − 24', v: 10 } },
    { who: 'samurai', say: 'Swap a hen for a goat and you add two legs. How many swaps make 10?', add: { t: '4 − 2', v: 2 } },
    { who: 'beaker', say: 'Five swaps — five goats, seven hens. And 7 × 2 + 5 × 4 is 34.', add: { t: '10 ÷ 2', v: 5 } },
  ] },
  'age-problems': { title: 'Twice as old', scene: 'festival', cast: ['goldlegend', 'comet'], beats: [
    { who: null, say: 'At a family festival, Dax (11) and his uncle (37) wonder when the uncle will be exactly twice as old as Dax.' },
    { who: 'comet', say: 'He is already more than twice as old. So never, right?' },
    { who: 'goldlegend', say: 'Look at the gap instead. It never changes.', add: { t: '37 − 11', v: 26 } },
    { who: 'goldlegend', say: 'Twice your age is your age and then your age again. That second one is the gap. So you will be 26.' },
    { who: 'comet', say: 'Then he will be 52, which IS twice 26.', add: { t: '(37 + 15) ÷ (11 + 15)', v: 2 } },
    { who: 'goldlegend', say: 'And 26 is this many years away.', add: { t: '26 − 11', v: 15 } },
  ] },
  'simpler-case': { title: 'The rope fence', scene: 'stadium', cast: ['scopey', 'pixel'], beats: [
    { who: null, say: 'For sports day, a 60-metre rope fence needs a post every 5 metres, with a post at each end.' },
    { who: 'pixel', say: 'That is 60 ÷ 5. Twelve posts. Done.', add: { t: '60 ÷ 5', v: 12 } },
    { who: 'scopey', say: 'Try a tiny one first: a 10-metre fence. Post, gap, post, gap, post.', add: { t: '10 ÷ 5', v: 2 } },
    { who: 'pixel', say: 'Two gaps but three posts! There is one more post than gaps.' },
    { who: 'scopey', say: 'So 12 is the gaps, not the posts.' },
    { who: 'pixel', say: 'Thirteen posts. The tiny fence caught me.', add: { t: '12 + 1', v: 13 } },
  ] },
  'meeting-and-overtaking': { title: 'Meeting at the bridge', scene: 'pond', cast: ['koi', 'panda'], beats: [
    { who: null, say: 'Nova and Suki stand at opposite ends of a 900-metre path round the pond. Nova walks 70 metres a minute, Suki 80.' },
    { who: 'koi', say: 'We both eat up the gap, so it shrinks by both our speeds each minute.', add: { t: '70 + 80', v: 150 } },
    { who: 'panda', say: 'Then we meet in this many minutes.', add: { t: '900 ÷ 150', v: 6 } },
    { who: 'koi', say: 'Check: my bit and your bit should make the whole path.', add: { t: '6 × 70 + 6 × 80', v: 900 } },
    { who: 'panda', say: 'So we meet where you have walked six minutes — at the little bridge.', add: { t: '6 × 70', v: 420 } },
  ] },
  'units-digit-cycles': { title: 'The last digit', scene: 'hall', cast: ['samurai', 'melody'], beats: [
    { who: null, say: 'In the school hall, Kwame writes a challenge: what is the last digit of 7 multiplied by itself 50 times?' },
    { who: 'melody', say: 'That number has more than 40 digits. Nobody can work it out.' },
    { who: 'samurai', say: 'We only need the last one. Watch the endings: 7, then…', add: { t: '7 × 7', v: 49 } },
    { who: 'melody', say: 'Then 343, then 2,401. The endings go 7, 9, 3, 1 — and then 7 again!', add: { t: '343 × 7', v: 2401 } },
    { who: 'samurai', say: 'A cycle of 4. Forty-eight is 12 cycles, which leaves this many steps.', add: { t: '50 − 12 × 4', v: 2 } },
    { who: 'melody', say: 'The second ending in the cycle is the 9 of 49 — take away the tens.', add: { t: '49 − 40', v: 9 } },
  ] },
};
