/* GENERATED by tools/build-landing-try.mjs from the stop's own work() — do not edit; test/light.mjs checks it. */
export const TRY = {
 "id": "column-add",
 "title": "Column addition",
 "text": "246 + 137",
 "steps": [
  {
   "t": "Ones: 6 + 7",
   "v": "13"
  },
  {
   "t": "Tens: 4 + 3 + 1 carried",
   "v": "8"
  },
  {
   "t": "Hundreds: 2 + 1",
   "v": "3"
  },
  {
   "t": "Keep the last digit of each column, carry the tens — read the answer",
   "v": "383"
  }
 ],
 "why": "Lining up the digits puts ones with ones, tens with tens, hundreds with hundreds. You can only add things of the same kind — 8 ones and 7 ones make 15 ones."
};
